<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <RootNamespace>LSEG.Ema.Access.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <AssemblyName>RTSDK.EmaTests</AssemblyName>
    <BaseOutputPath>$(ProjectDir)..\..\Executables\RTSDK.EmaTests</BaseOutputPath>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsPublishable>False</IsPublishable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>namekeys.snk</AssemblyOriginatorKeyFile>
    <DelaySign>true</DelaySign>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS8002</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS8002</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="testconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AspectInjector" Version="2.9.0" />
    <PackageReference Include="FakeItEasy" Version="9.0.1" />
    <PackageReference Include="FakeItEasy.Analyzer.CSharp" Version="6.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Eta\Src\TestsCommon\RTSDK.Tests.Common.csproj" />
    <ProjectReference Include="..\..\..\Eta\Src\ValueAdd\ValueAdd.csproj" />
    <ProjectReference Include="..\Core\EMA_Core.csproj" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Message Text="Copy enumtype.def and RDMFieldDictionary to output directory" Importance="high" />
    <Copy SourceFiles="$(ProjectDir)/ComplexTypeTests/enumtype.def" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="$(ProjectDir)/ComplexTypeTests/RDMFieldDictionary" DestinationFolder="$(OutDir)" />
  </Target>

</Project>
