apply plugin: 'application'

eclipse {
        project {
                name = 'RTSDK-Eta-Examples'
        }
}

dependencies {
	implementation project(':Eta:AnsiPage')
	implementation project(':Eta:ValueAdd')
	implementation project(':Eta:ValueAddCache')
	implementation project(':Eta:Applications:Shared')
	implementation project(':Eta:Applications:PerfTools').sourceSets.main.output
	implementation group: 'xpp3', name: 'xpp3', version: '1.1.4c'
	// Adding dependency on the jdacsEtalib.jar
	implementation fileTree(dir: '../../../../RTSDK-BinaryPack/Java/Eta/Libs', include: 'jdacsEtalib.jar')
	implementation fileTree(dir: '../../Libs', include: 'jdacsEtalib.jar')
}

application {
	mainClass = 'com.refinitiv.eta.examples.provider.Provider'
}

tasks.register('createExtraRunApp', CreateStartScripts) {
    mainClass.set('main.java.com.refinitiv.eta.examples.consumer.Consumer')
    classpath = startScripts.classpath
    outputDir = startScripts.outputDir
    applicationName = 'myconsumer'
}

tasks.register('copyDictionary') {
    outputs.files files('../../../etc')
            .asFileTree
            .files
            .collect { './${it.name}' }

    doLast {
        copy {
            from '../../../etc'
            into './'
        }
    }
}

tasks.register('deleteDictionary', Delete) {
    delete "$projectDir/RDMFieldDictionary"
    delete "$projectDir/RDMFieldDictionary_large"
    delete "$projectDir/enumtype.def"
}

run.dependsOn copyDictionary
clean.dependsOn deleteDictionary

tasks.register('runProvider', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.provider.Provider')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runConsumer', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.consumer.Consumer')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runNIProvider', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.niprovider.NIProvider')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runVAProvider', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.valueadd.examples.provider.Provider')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runVAConsumer', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.valueadd.examples.consumer.Consumer')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runVANIProvider', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.valueadd.examples.niprovider.NIProvider')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runWatchlistConsumer', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.valueadd.examples.watchlistconsumer.WatchlistConsumer')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runGenericProv', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.genericprov.GenericProv')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runGenericCons', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.genericcons.GenericCons')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runNewsViewer', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.newsviewer.NewsViewer')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runAnsiPageExample', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.ansipage.AnsiPageExample')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runCodecExample', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.codec.CodecExample')
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('runAuthLockExample', JavaExec) {
    dependsOn 'copyDictionary'

    mainClass.set('com.refinitiv.eta.examples.authlock.AuthLockExample')
    classpath = sourceSets.main.runtimeClasspath
}

