<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LSEG.Eta.Tests.Common</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspectInjector" Version="2.9.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
    <PackageReference Include="xunit.v3.assert" Version="4.0.0" />
  </ItemGroup>

</Project>
