/*|-----------------------------------------------------------------------------
 *|            This source code is provided under the Apache 2.0 license      --
 *|  and is provided AS IS with no warranty or guarantee of fit for purpose.  --
 *|                See the project's LICENSE.md for details.                  --
 *|           Copyright (C) 2019 Refinitiv. All rights reserved.            --
 *|-----------------------------------------------------------------------------
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thomsonreuters_upa_transport_JNIChannel */

#ifndef _Included_com_thomsonreuters_upa_transport_JNIChannel
#define _Included_com_thomsonreuters_upa_transport_JNIChannel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslGetChannelInfo
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ChannelInfoImpl;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslGetChannelInfo
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslIoctl
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;ILjava/lang/Object;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslIoctl
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslBufferUsage
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslBufferUsage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslInitChannel
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/InProgInfoImpl;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslInitChannel
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslCloseChannel
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslCloseChannel
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslRead
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ReadArgsImpl;Lcom/thomsonreuters/upa/transport/ErrorImpl;)Lcom/thomsonreuters/upa/transport/JNIBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslRead
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslGetBuffer
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;IZLcom/thomsonreuters/upa/transport/ErrorImpl;)Lcom/thomsonreuters/upa/transport/JNIBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslGetBuffer
  (JNIEnv *, jobject, jobject, jint, jboolean, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslReleaseBuffer
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIBuffer;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslReleaseBuffer
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslPackBuffer
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/JNIBuffer;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslPackBuffer
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslWrite
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/JNIBuffer;Lcom/thomsonreuters/upa/transport/WriteArgsImpl;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslWrite
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslFlush
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslFlush
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslPing
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslPing
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIChannel
 * Method:    rsslReconnectClient
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIChannel_rsslReconnectClient
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_ShMemChannel
 * Method:    rsslShMemServerSeqNum
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;)J
 */
JNIEXPORT jlong JNICALL Java_com_thomsonreuters_upa_transport_ShMemChannel_rsslShMemServerSeqNum
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_ShMemChannel
 * Method:    rsslShMemFlags
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIChannel;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_ShMemChannel_rsslShMemFlags
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
