/*|-----------------------------------------------------------------------------
 *|            This source code is provided under the Apache 2.0 license      --
 *|  and is provided AS IS with no warranty or guarantee of fit for purpose.  --
 *|                See the project's LICENSE.md for details.                  --
 *|           Copyright Thomson Reuters 2018. All rights reserved.            --
 *|-----------------------------------------------------------------------------
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thomsonreuters_upa_transport_JNIServer */

#ifndef _Included_com_thomsonreuters_upa_transport_JNIServer
#define _Included_com_thomsonreuters_upa_transport_JNIServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thomsonreuters_upa_transport_JNIServer
 * Method:    rsslGetServerInfo
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIServer;Lcom/thomsonreuters/upa/transport/ServerInfoImpl;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIServer_rsslGetServerInfo
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIServer
 * Method:    rsslServerIoctl
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIServer;ILjava/lang/Object;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIServer_rsslServerIoctl
  (JNIEnv *, jobject, jobject, jint, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIServer
 * Method:    rsslServerBufferUsage
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIServer;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIServer_rsslServerBufferUsage
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_thomsonreuters_upa_transport_JNIServer
 * Method:    rsslCloseServer
 * Signature: (Lcom/thomsonreuters/upa/transport/JNIServer;Lcom/thomsonreuters/upa/transport/ErrorImpl;)I
 */
JNIEXPORT jint JNICALL Java_com_thomsonreuters_upa_transport_JNIServer_rsslCloseServer
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
