Transport API Value Addded Components Reference Manual: RSSL RDM Dictionary Codec
RSSL RDM Dictionary Codec
RSSL RDM Codec API
The RSSL RDM Dictionary component is intended to assist developers with encoding and decoding messages used by the Dictionary Reuters Domain Model. This component provides typed data structures, encoding and decoding functions for Dictionary Domain messages.
Data Structures
struct RsslRDMDictionaryRequest
The RDM Dictionary Request. Used by an OMM Consumer to request a dictionary from a services that provides it.
struct RsslRDMDictionaryRefresh
The RDM Dictionary Refresh. Used by an OMM Provider to provide the content of a Dictionary.
NOTE: The Field dictionary type supports being split into fragments, each containing some of the fields. rsslEncodeRDMDictionaryMsg() may need to be called multiple times to send the entire message. The startFid parameter will be updated with each call.
struct RsslRDMDictionaryClose
The RDM Dictionary Close. Used by an OMM Consumer to close a Dictionary stream.
struct RsslRDMDictionaryStatus
The RDM Dictionary Status. Used by an OMM Provider to indicate changes to the Dictionary stream.
union RsslRDMDictionaryMsg
The RDM Dictionary Msg. The Dictionary Message encoder and decoder functions expect this type. It is a group of the classes of message that the Dictionary domain supports. Any specific message class may be cast to an RsslRDMDictionaryMsg, and an RsslRDMDictionaryMsg may be cast to any specific message class. The RsslRDMMsgBase contains members common to each class that may be used to identify the class of message.
Modules
RDM Dictionary Helper Functions
Enumerations
enum RsslRDMDictionaryMsgType {
RDM_DC_MT_UNKNOWN = 0,
RDM_DC_MT_REQUEST = 1,
RDM_DC_MT_CLOSE = 2,
RDM_DC_MT_REFRESH = 3,
RDM_DC_MT_STATUS = 4
}
The types of RDM Dictionary Messages. When the rdmMsgBase's domainType is RSSL_DMT_DICTIONARY, the rdmMsgType member may be set to one of these to indicate the specific RsslRDMDictionaryMsg class.
enum RsslRDMDictionaryRequestFlags {
RDM_DC_RQF_NONE = 0x0,
RDM_DC_RQF_STREAMING = 0x1
}
The RDM Dictionary Request Flags.
enum RsslRDMDictionaryRefreshFlags {
RDM_DC_RFF_NONE = 0x00,
RDM_DC_RFF_HAS_INFO = 0x01,
RDM_DC_RFF_IS_COMPLETE = 0x02,
RDM_DC_RFF_SOLICITED = 0x04,
RDM_DC_RFF_HAS_SEQ_NUM = 0x08,
RDM_DC_RFF_CLEAR_CACHE = 0x10
}
The RDM Dictionary Refresh Flags.
enum RsslRDMDictionaryStatusFlags {
RDM_DC_STF_NONE = 0x00,
RDM_DC_STF_HAS_STATE = 0x01
}
The RDM Dictionary Status Flags.
Functions
RTR_C_INLINE void rsslClearRDMDictionaryRequest (RsslRDMDictionaryRequest *pRequest)
Clears an RsslRDMDictionaryRequest.
RTR_C_INLINE void rsslClearRDMDictionaryRefresh (RsslRDMDictionaryRefresh *pDictionaryRefresh)
Clears an RsslRDMDictionaryRefresh.
RTR_C_INLINE void rsslClearRDMDictionaryClose (RsslRDMDictionaryClose *pClose)
Clears an RsslRDMDictionaryClose.
RTR_C_INLINE void rsslClearRDMDictionaryStatus (RsslRDMDictionaryStatus *pStatus)
Clears an RsslRDMDictionaryStatus.
RTR_C_INLINE void rsslClearRDMDictionaryMsg (RsslRDMDictionaryMsg *pMsg)
Clears an RsslRDMDictionaryMsg.
RSSL_VA_API RsslRet rsslEncodeRDMDictionaryMsg (RsslEncodeIterator *pEncodeIter, RsslRDMDictionaryMsg *pDictionaryMsg, RsslUInt32 *pBytesWritten, RsslErrorInfo *pError)
Encodes an RsslRDMDictionaryMsg.
When encoding an RsslRDMDictionaryRefresh of type RDM_DICTIONARY_FIELD_DEFINITIONS, this function may need to be called multiple times to send the entire refresh. This is because the Field Dictionary supports being split into fragments when encoding. When this occurs, RSSL_RET_DICT_PART_ENCODED is returned instead of RSSL_RET_SUCCESS and the RsslRDMDictionaryRefresh structure is updated. To continue encoding, set pEncodeIter to a new RsslBuffer and call rsslEncodeRDMDictionaryMsg() again.
RSSL_VA_API RsslRet rsslDecodeRDMDictionaryMsg (RsslDecodeIterator *pIter, RsslMsg *pMsg, RsslRDMDictionaryMsg *pDictionaryMsg, RsslBuffer *pMemoryBuffer, RsslErrorInfo *pError)
Decodes an RsslRDMDictionaryMsg.
Enumeration Type Documentation
enum RsslRDMDictionaryMsgType
See also:
RsslRDMDictionaryMsg, RsslRDMMsgBase, RsslRDMDictionaryRequest, RsslRDMDictionaryClose, RsslRDMDictionaryRefresh, RsslRDMDictionaryStatus
Enumerator:
RDM_DC_MT_UNKNOWN
(0) Unknown type.
RDM_DC_MT_REQUEST
(1) Dictionary Request.
RDM_DC_MT_CLOSE
(2) Dictionary Close.
RDM_DC_MT_REFRESH
(3) Dictionary Refresh.
RDM_DC_MT_STATUS
(4) Dictionary Status.
enum RsslRDMDictionaryRefreshFlags
See also:
RsslRDMDictionaryRefresh
Enumerator:
RDM_DC_RFF_NONE
(0x00) No flags set.
RDM_DC_RFF_HAS_INFO
(0x01) When decoding, indicates presence of the dictionaryId, version, and type members. This flag is not used while encoding as this information is automatically added by the encode function when appropriate.
RDM_DC_RFF_IS_COMPLETE
(0x02) When decoding, indicates that this is the final part of the dictionary refresh. This flag is not used while encoding as it is automatically set by the encode function set when appropriate.
RDM_DC_RFF_SOLICITED
(0x04) Indicates that this refresh is being provided in response to a request.
RDM_DC_RFF_HAS_SEQ_NUM
(0x08) Indicates presence of the sequenceNumber member.
RDM_DC_RFF_CLEAR_CACHE
(0x10) Indicates the receiver of the refresh should clear any existing cached information.
enum RsslRDMDictionaryRequestFlags
See also:
RsslRDMDictionaryRequest
Enumerator:
RDM_DC_RQF_NONE
(0x0) No flags set.
RDM_DC_RQF_STREAMING
(0x1) Indicates this is to be a streaming request.
enum RsslRDMDictionaryStatusFlags
See also:
RsslRDMDictionaryStatus
Enumerator:
RDM_DC_STF_NONE
(0x00) No flags set.
RDM_DC_STF_HAS_STATE
(0x01) Indicates presence of the state member.
Function Documentation
RTR_C_INLINE void rsslClearRDMDictionaryClose (RsslRDMDictionaryClose * pClose)
See also:
RsslRDMDictionaryClose
References RsslRDMMsgBase::domainType, RDM_DC_MT_CLOSE, RsslRDMDictionaryClose::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, and rsslClearRDMMsgBase().
RTR_C_INLINE void rsslClearRDMDictionaryMsg (RsslRDMDictionaryMsg * pMsg)
See also:
RsslRDMDictionaryMsg
References RsslRDMMsgBase::domainType, and RsslRDMDictionaryMsg::rdmMsgBase.
RTR_C_INLINE void rsslClearRDMDictionaryRefresh (RsslRDMDictionaryRefresh * pDictionaryRefresh)
See also:
RsslRDMDictionaryRefresh
References RsslRDMDictionaryRefresh::dataBody, RsslRDMDictionaryRefresh::dictionaryId, RsslRDMDictionaryRefresh::dictionaryName, RsslRDMMsgBase::domainType, RsslRDMDictionaryRefresh::enumStartFid, RsslRDMDictionaryRefresh::flags, RsslRDMDictionaryRefresh::pDictionary, RDM_DC_MT_REFRESH, RDM_DC_RFF_NONE, RsslRDMDictionaryRefresh::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMDictionaryRefresh::sequenceNumber, RsslRDMDictionaryRefresh::serviceId, RsslRDMDictionaryRefresh::startFid, RsslRDMDictionaryRefresh::state, RsslRDMDictionaryRefresh::type, RsslRDMDictionaryRefresh::verbosity, and RsslRDMDictionaryRefresh::version.
RTR_C_INLINE void rsslClearRDMDictionaryRequest (RsslRDMDictionaryRequest * pRequest)
See also:
RsslRDMDictionaryRequest
References RsslRDMDictionaryRequest::dictionaryName, RsslRDMMsgBase::domainType, RsslRDMDictionaryRequest::flags, RDM_DC_MT_REQUEST, RDM_DC_RQF_NONE, RsslRDMDictionaryRequest::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMDictionaryRequest::serviceId, and RsslRDMDictionaryRequest::verbosity.
RTR_C_INLINE void rsslClearRDMDictionaryStatus (RsslRDMDictionaryStatus * pStatus)
See also:
RsslRDMDictionaryStatus
References RsslRDMMsgBase::domainType, RsslRDMDictionaryStatus::flags, RDM_DC_MT_STATUS, RDM_DC_STF_NONE, RsslRDMDictionaryStatus::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), and RsslRDMDictionaryStatus::state.
RSSL_VA_API RsslRet rsslDecodeRDMDictionaryMsg (RsslDecodeIterator * pIter, RsslMsg * pMsg, RsslRDMDictionaryMsg * pDictionaryMsg, RsslBuffer * pMemoryBuffer, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Decode Iterator
pDictionaryMsg The RDM Dictionary Message to be populated
pMemoryBuffer An RsslBuffer pointing to space that may be used as additional storage space for the decoded message.
pError An Error Structure, which will be populated if the decoding fails.
Returns:
RSSL_RET_SUCCESS, if the message was succesfully decoded and correctly followed the RDM.
RSSL_RET_FAILURE, if the message was not successfully decoded or did follow the RDM. Information about the error will be stored in pError.
RSSL_RET_BUFFER_TOO_SMALL, if the size of pNewMemoryBuffer was not large enough to store all additional data.
See also:
RsslRDMDictionaryMsg
Referenced by rsslDecodeRDMMsg().
RSSL_VA_API RsslRet rsslEncodeRDMDictionaryMsg (RsslEncodeIterator * pEncodeIter, RsslRDMDictionaryMsg * pDictionaryMsg, RsslUInt32 * pBytesWritten, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Encode Iterator
pDictionaryMsg The RDM Dictionary Message to Encode
pBytesWritten Returns the total number of bytes used to encode the message.
Returns:
RSSL_RET_SUCCESS when successful.
RSSL_RET_DICT_PART_ENCODED, when encoding was successful but there is still more data in the dictionary to send.
See also:
RsslRDMDictionaryMsg
Referenced by rsslEncodeRDMMsg().