Transport API Value Addded Components Reference Manual: RSSL Reactor Channel Operation Functions
RSSL Reactor Channel Operation Functions
RSSL Reactor Channel Structure
The RSSL Reactor Channel operation functions are used to perform channel-specific actions.
Functions
RTR_C_INLINE RsslBuffer * rsslReactorGetBuffer (RsslReactorChannel *pReactorChannel, RsslUInt32 size, RsslBool packedBuffer, RsslErrorInfo *pError)
Gets a buffer from the RsslReactorChannel for writing a message.
RTR_C_INLINE RsslRet rsslReactorReleaseBuffer (RsslReactorChannel *pReactorChannel, RsslBuffer *pBuffer, RsslErrorInfo *pError)
Returns an unwritten buffer to the RsslReactorChannel.
RTR_C_INLINE RsslBuffer * rsslReactorPackBuffer (RsslReactorChannel *pReactorChannel, RsslBuffer *pBuffer, RsslErrorInfo *pError)
Packs an RsslBuffer and returns a new position in the buffer for writing another message.
RTR_C_INLINE RsslRet rsslReactorChannelIoctl (RsslReactorChannel *pReactorChannel, int code, void *value, RsslErrorInfo *pError)
Changes some aspects of the RsslReactorChannel.
Function Documentation
RTR_C_INLINE RsslRet rsslReactorChannelIoctl (RsslReactorChannel * pReactorChannel, int code, void * value, RsslErrorInfo * pError)
Parameters:
pReactorChannel The channel to be modified.
code Code indicating the option to change. See RsslIoctlCodes.
value Value to change the option to.
pError Error structure to be populated in the event of failure.
Returns:
RsslRet return codes
See also:
RsslReactor, RsslReactorChannel, RsslIoctlCodes, RsslErrorInfo
References RsslReactorChannel::pRsslChannel, RsslErrorInfo::rsslError, and rsslSetErrorInfoLocation().
RTR_C_INLINE RsslBuffer* rsslReactorGetBuffer (RsslReactorChannel * pReactorChannel, RsslUInt32 size, RsslBool packedBuffer, RsslErrorInfo * pError)
Parameters:
pChannel The channel to get a buffer for.
size The size(in bytes) of the buffer to get.
packedBuffer whether the buffer allows packing multiple messages via rsslReactorPackBuffer().
pError Error structure to be populated in the event of failure.
Returns:
The buffer for writing the message.
NULL, if an error occured. pError will be populated with information.
See also:
RsslReactor, RsslErrorInfo, rsslReactorPackBuffer, rsslReactorSubmit, rsslReactorReleaseBuffer
References RsslReactorChannel::pRsslChannel, RsslErrorInfo::rsslError, and rsslSetErrorInfoLocation().
RTR_C_INLINE RsslBuffer* rsslReactorPackBuffer (RsslReactorChannel * pReactorChannel, RsslBuffer * pBuffer, RsslErrorInfo * pError)
Parameters:
pReactorChannel The channel that owns the RsslBuffer.
pBuffer The buffer to be packed. The length should be set to the size of the currently written message.
pError Error structure to be populated in the event of failure.
Returns:
A new buffer position to begin writing to.
NULL, if an error occurred.
See also:
RsslReactor, RsslReactorChannel, RsslBuffer, RsslErrorInfo
References RsslReactorChannel::pRsslChannel, RsslErrorInfo::rsslError, and rsslSetErrorInfoLocation().
RTR_C_INLINE RsslRet rsslReactorReleaseBuffer (RsslReactorChannel * pReactorChannel, RsslBuffer * pBuffer, RsslErrorInfo * pError)
Parameters:
pChannel The channel to get a buffer for.
pBuffer The buffer to release.
pError Error structure to be populated in the event of failure.
Returns:
RsslRet codes.
See also:
RsslReactor, RsslReactorChannel, RsslErrorInfo, rsslReactorGetBuffer, rsslReactorSubmit
References RsslErrorInfo::rsslError, and rsslSetErrorInfoLocation().