Transport API Value Addded Components Reference Manual: RSSL RDM Message Base Structure
RSSL RDM Message Base Structure
RSSL RDM Codec Common Structures
The RDM Message Base structure is used by all Value Added RDM message structures.
Data Structures
struct RsslRDMMsgBase
This message structure contains the information that is common across all RDM Message formats. It is included in all Value Added RDM Components.
Functions
RTR_C_INLINE void rsslClearRDMMsgBase (RsslRDMMsgBase *pBase)
This is used to clear the data contained in the RsslRDMMsgBase structure.
Function Documentation
RTR_C_INLINE void rsslClearRDMMsgBase (RsslRDMMsgBase * pBase)
References RsslRDMMsgBase::domainType, RsslRDMMsgBase::rdmMsgType, and RsslRDMMsgBase::streamId.
Referenced by rsslClearRDMDictionaryClose(), rsslClearRDMDictionaryRefresh(), rsslClearRDMDictionaryRequest(), rsslClearRDMDictionaryStatus(), rsslClearRDMDirectoryConsumerStatus(), rsslClearRDMDirectoryRefresh(), rsslClearRDMDirectoryRequest(), rsslClearRDMDirectoryStatus(), rsslClearRDMDirectoryUpdate(), rsslClearRDMLoginClose(), rsslClearRDMLoginConsumerConnectionStatus(), rsslClearRDMLoginRefresh(), rsslClearRDMLoginRequest(), and rsslClearRDMLoginStatus().