Transport API Value Addded Components Reference Manual: RSSL Value Add Utility Components
RSSL Value Add Utility Components
API Value Added Components
The Value Add Utility component contains helper structures and funcions used by the entire Transport API Value Added package.
Data Structures
struct RsslErrorInfo
Error Information. Used by RsslRDMMsg encode and decode functions, as well as the RsslReactor.
Defines
#define RSSL_ERROR_INFO_LOCATION_LENGTH (1024)
#define RSSL_ERROR_INFO_CHECK(__cond, __ret, __pError) ((__cond) || (rsslSetErrorInfo((__pError), RSSL_EIC_FAILURE, (__ret), __FILE__, __LINE__, (#__cond)), 0))
Checks the given condition. If the condition is false, calls rsslSetErrorInfo() with a string representing the condition and the current location in the source code.
Enumerations
enum RsslErrorInfoCode {
RSSL_EIC_SUCCESS = 0,
RSSL_EIC_FAILURE = -1
}
Error Codes for RsslErrorInfo.
Functions
RTR_C_INLINE void rsslSetErrorInfoLocation (RsslErrorInfo *pError, const char *fileName, int lineNum)
Sets a given file:line location on an RsslErrorInfo structure. Typically used by the RsslReactor when the rsslError member has been set by a function call.
RTR_C_INLINE void rsslSetErrorInfo (RsslErrorInfo *pError, RsslErrorInfoCode errorInfoCode, RsslRet rsslCode, const char *fileName, int lineNum, const char *errorString,...)
Sets the given error information and file:line location on an RsslErrorInfo structure.
RTR_C_INLINE void rsslCopyErrorInfo (RsslErrorInfo *pNewError, RsslErrorInfo *pOldError)
Copies an RsslErrorInfo structure.
RSSL_VA_API void * rsslReserveBufferMemory (RsslBuffer *pBuffer, RsslUInt32 elementCount, RsslUInt32 sizeofElement)
Reserves a portion of an RsslBuffer for use as an array of one or more elements.
RSSL_VA_API void * rsslReserveAlignedBufferMemory (RsslBuffer *pBuffer, RsslUInt32 elementCount, RsslUInt32 sizeOfElement)
Reserves a portion of an RsslBuffer for use as an array of one or more elements. Works like rsslReserveBufferMemory() but first aligns the memory on a boundary appropriate for the size of the element.
RSSL_VA_API char * rsslCopyBufferMemory (RsslBuffer *pOutBuf, RsslBuffer *pInBuf, RsslBuffer *pMemoryBuffer)
Reserves a portion of an RsslBuffer for use as a string and copies the given string.
RTR_C_INLINE RsslRet rsslDeepCopyConnectOpts (RsslConnectOptions *destOpts, RsslConnectOptions *sourceOpts)
Performs a deep copy of a rsslConnectOpts structure.
RTR_C_INLINE void rsslFreeConnectOpts (RsslConnectOptions *connOpts)
static RsslRDMMsg * rsslCreateRDMMsgCopy (RsslRDMMsg *pRdmMsg, RsslUInt32 lengthHint, RsslRet *pRet)
Creates a deep copy of an RsslRDMMsg.
Define Documentation
#define RSSL_ERROR_INFO_CHECK (__cond, __ret, __pError) ((__cond) || (rsslSetErrorInfo((__pError), RSSL_EIC_FAILURE, (__ret), __FILE__, __LINE__, (#__cond)), 0))
See also:
RsslErrorInfo
#define RSSL_ERROR_INFO_LOCATION_LENGTH (1024)
Referenced by rsslCopyErrorInfo(), and rsslSetErrorInfoLocation().
Enumeration Type Documentation
enum RsslErrorInfoCode
See also:
RsslErrorInfo
Enumerator:
RSSL_EIC_SUCCESS
Success
RSSL_EIC_FAILURE
General failure
Function Documentation
RSSL_VA_API char* rsslCopyBufferMemory (RsslBuffer * pOutBuf, RsslBuffer * pInBuf, RsslBuffer * pMemoryBuffer)
Parameters:
pOutBuf the RsslBuffer that will be populated to point to the copy of the string.
pInBuf the RsslBuffer containing the string to copy.
pMemoryBuffer RsslBuffer pointing to memory that will be used to hold the string. The buffer will be changed to point to the remaining unused memory.
Returns:
Pointer to the start of the reserved memory.
NULL if the buffer did not have enough space for the requested memory.
See also:
rsslReserveBufferMemory, rsslReserveAlignedBufferMemory
RTR_C_INLINE void rsslCopyErrorInfo (RsslErrorInfo * pNewError, RsslErrorInfo * pOldError)
See also:
RsslErrorInfo
References RsslErrorInfo::errorLocation, RSSL_ERROR_INFO_LOCATION_LENGTH, RsslErrorInfo::rsslError, and RsslErrorInfo::rsslErrorInfoCode.
static RsslRDMMsg* rsslCreateRDMMsgCopy (RsslRDMMsg * pRdmMsg, RsslUInt32 lengthHint, RsslRet * pRet) [static]
Parameters:
pRdmMsg RsslRDMMsg to copy.
lengthHint An initial size for the memory buffer created. If this is too small a larger size will be allocated.
Returns:
The created RDMMsg, or NULL if an error occurred. If so, pRet is populated with:
RSSL_RET_INVALID_ARGUMENT, if the message appears invalid.
RSSL_RET_BUFFER_NO_BUFFERS, if memory could not be allocated.
RSSL_RET_FAILURE, if the message could not be copied for some other reason.
References rsslCopyRDMMsg().
RTR_C_INLINE RsslRet rsslDeepCopyConnectOpts (RsslConnectOptions * destOpts, RsslConnectOptions * sourceOpts)
Parameters:
destOpts RsslConnectOpts to be copied to.
sourceOpts RsslConnectOpts to be copied from.
Returns:
RSSL_RET_SUCCESS if successful, RSSL_RET_FAILURE if an error occurred.
RTR_C_INLINE void rsslFreeConnectOpts (RsslConnectOptions * connOpts)
RSSL_VA_API void* rsslReserveAlignedBufferMemory (RsslBuffer * pBuffer, RsslUInt32 elementCount, RsslUInt32 sizeOfElement)
Parameters:
pBuffer The buffer to apportion from. The buffer will be changed to point to the remaining unused memory.
elementCount The number of elements of to reserve.
sizeOfElement The size of the element(s) to reserve.
Returns:
Pointer to the start of the reserved memory.
NULL if the buffer did not have enough space for the requested memory.
See also:
rsslReserveBufferMemory, rsslCopyBufferMemory
RSSL_VA_API void* rsslReserveBufferMemory (RsslBuffer * pBuffer, RsslUInt32 elementCount, RsslUInt32 sizeofElement)
Parameters:
pBuffer The buffer to apportion from. The buffer will be changed to point to the remaining unused memory.
elementCount The number of elements of to reserve.
sizeOfElement The size of the element(s) to reserve.
Returns:
Pointer to the start of the reserved memory.
NULL if the buffer did not have enough space for the requested memory.
See also:
rsslReserveAlignedBufferMemory, rsslCopyBufferMemory
RTR_C_INLINE void rsslSetErrorInfo (RsslErrorInfo * pError, RsslErrorInfoCode errorInfoCode, RsslRet rsslCode, const char * fileName, int lineNum, const char * errorString, ...)
See also:
RsslErrorInfo
References RsslErrorInfo::rsslError, RsslErrorInfo::rsslErrorInfoCode, and rsslSetErrorInfoLocation().
Referenced by rsslHashTableInit(), rsslMemoryPoolGet(), and rsslMemoryPoolInit().
RTR_C_INLINE void rsslSetErrorInfoLocation (RsslErrorInfo * pError, const char * fileName, int lineNum)
See also:
RsslErrorInfo
References RsslErrorInfo::errorLocation, and RSSL_ERROR_INFO_LOCATION_LENGTH.
Referenced by rsslReactorChannelBufferUsage(), rsslReactorChannelIoctl(), rsslReactorGetBuffer(), rsslReactorGetChannelInfo(), rsslReactorPackBuffer(), rsslReactorReleaseBuffer(), and rsslSetErrorInfo().