Transport API Value Addded Components Reference Manual: RSSL RDM Codec Common Structures
RSSL RDM Codec Common Structures
RSSL RDM Codec API
The RSSL RDM Codec Common Structures are used by all of the Value Added RDM components.
Data Structures
union RsslRDMMsg
RSSL Message Union contains all messages. This includes constructs, functions, and values.
Modules
RSSL RDM Message Base Structure
The RDM Message Base structure is used by all Value Added RDM message structures.
Functions
RTR_C_INLINE void rsslClearRDMMsg (RsslRDMMsg *pMsg)
RTR_C_INLINE RsslRet rsslEncodeRDMMsg (RsslEncodeIterator *pIter, RsslRDMMsg *pRDMMsg, RsslUInt32 *pBytesWritten, RsslErrorInfo *pError)
This function encodes the given RDM Message.
RTR_C_INLINE RsslRet rsslDecodeRDMMsg (RsslDecodeIterator *pIter, RsslMsg *pMsg, RsslRDMMsg *pRDMMsg, RsslBuffer *pMemoryBuffer, RsslErrorInfo *pError)
Attempts to decode an Rssl message buffer into a domain message structure.
RTR_C_INLINE RsslRet rsslCopyRDMMsg (RsslRDMMsg *pNewMsg, RsslRDMMsg *pOldMsg, RsslBuffer *pNewMemoryBuffer)
Copies the pOldMsg to pNewMsg.
Function Documentation
RTR_C_INLINE void rsslClearRDMMsg (RsslRDMMsg * pMsg)
RTR_C_INLINE RsslRet rsslCopyRDMMsg (RsslRDMMsg * pNewMsg, RsslRDMMsg * pOldMsg, RsslBuffer * pNewMemoryBuffer)
References RsslRDMMsgBase::domainType, RsslRDMMsg::rdmMsgBase, rsslCopyRDMDictionaryMsg(), rsslCopyRDMDirectoryMsg(), and rsslCopyRDMLoginMsg().
Referenced by rsslCreateRDMMsgCopy().
RTR_C_INLINE RsslRet rsslDecodeRDMMsg (RsslDecodeIterator * pIter, RsslMsg * pMsg, RsslRDMMsg * pRDMMsg, RsslBuffer * pMemoryBuffer, RsslErrorInfo * pError)
References RsslRDMMsgBase::domainType, RsslRDMDictionaryMsg::rdmMsgBase, rsslDecodeRDMDictionaryMsg(), rsslDecodeRDMDirectoryMsg(), and rsslDecodeRDMLoginMsg().
RTR_C_INLINE RsslRet rsslEncodeRDMMsg (RsslEncodeIterator * pIter, RsslRDMMsg * pRDMMsg, RsslUInt32 * pBytesWritten, RsslErrorInfo * pError)
References RsslRDMMsgBase::domainType, RsslRDMMsg::rdmMsgBase, rsslEncodeRDMDictionaryMsg(), rsslEncodeRDMDirectoryMsg(), and rsslEncodeRDMLoginMsg().