Transport API Value Addded Components Reference Manual: RSSL RDM Login Codec
RSSL RDM Login Codec
RSSL RDM Codec API
The RSSL RDM Login component is intended to assist developers with encoding and decoding messages used by the Login Reuters Domain Model. This component provides typed data structures, encoding and decoding functions for Login Domain messages.
Data Structures
struct RsslRDMLoginWarmStandbyInfo
Warm Standby Information for the RDM Login Consumer Connection Status.
struct RsslRDMServerInfo
Information about an available Server. A list of RsslRDMServerInfo is used by an RsslRDMLoginRefresh to list servers available for connecting to, and whether to use them as Standby servers.
struct RsslRDMLoginRequest
The RDM Login Request. Used by an OMM Consumer or OMM Noninteractive Provider to request a login.
struct RsslRDMLoginRefresh
The RDM Login Refresh. Used by an OMM Provider to accept or reject a login request and provide information about features supported.
struct RsslRDMLoginClose
The RDM Login Close. Used by an OMM Consumer or OMM Noninteractive Provider to close a login.
struct RsslRDMLoginStatus
The RDM Login Status. Used by an OMM Provider to indicate changes to the Login stream.
struct RsslRDMLoginConsumerConnectionStatus
The RDM Login Consumer Connection Status. Used by an OMM Consumer to send Warm Standby information.
union RsslRDMLoginMsg
The RDM Login Msg. The Login Message encoder and decoder functions expect this type. It is a group of the classes of message that the Login domain supports. Any specific message class may be cast to an RsslRDMLoginMsg, and an RsslRDMLoginMsg may be cast to any specific message class. The RsslRDMMsgBase contains members common to each class that may be used to identify the class of message.
Modules
RDM Login Helper Functions
Enumerations
enum RsslRDMServerInfoFlags {
RDM_LG_SIF_NONE = 0x00,
RDM_LG_SIF_HAS_LOAD_FACTOR = 0x01,
RDM_LG_SIF_HAS_TYPE = 0x02
}
The RDM Login Server Info Flags.
enum RsslRDMLoginMsgType {
RDM_LG_MT_UNKNOWN = 0,
RDM_LG_MT_REQUEST = 1,
RDM_LG_MT_CLOSE = 2,
RDM_LG_MT_CONSUMER_CONNECTION_STATUS = 3,
RDM_LG_MT_REFRESH = 4,
RDM_LG_MT_STATUS = 5,
RDM_LG_MT_POST = 6,
RDM_LG_MT_ACK = 7
}
The types of RDM Login Messages. When the rdmMsgBase's domainType is RSSL_DMT_LOGIN, the rdmMsgType member may be set to one of these to indicate the specific RsslRDMLoginMsg class.
enum RsslRDMLoginRequestFlags {
RDM_LG_RQF_NONE = 0x000000,
RDM_LG_RQF_HAS_ALLOW_SUSPECT_DATA = 0x000001,
RDM_LG_RQF_HAS_APPLICATION_ID = 0x000002,
RDM_LG_RQF_HAS_APPLICATION_NAME = 0x000004,
RDM_LG_RQF_HAS_DOWNLOAD_CONN_CONFIG = 0x000008,
RDM_LG_RQF_HAS_INSTANCE_ID = 0x000010,
RDM_LG_RQF_HAS_PASSWORD = 0x000020,
RDM_LG_RQF_HAS_POSITION = 0x000040,
RDM_LG_RQF_HAS_PROVIDE_PERM_EXPR = 0x000080,
RDM_LG_RQF_HAS_PROVIDE_PERM_PROFILE = 0x000100,
RDM_LG_RQF_HAS_ROLE = 0x000200,
RDM_LG_RQF_HAS_SINGLE_OPEN = 0x000400,
RDM_LG_RQF_HAS_USERNAME_TYPE = 0x000800,
RDM_LG_RQF_NO_REFRESH = 0x001000,
RDM_LG_RQF_PAUSE_ALL = 0x002000,
RDM_LG_RQF_HAS_SUPPORT_PROV_DIC_DOWNLOAD = 0x004000,
RDM_LG_RQF_HAS_APPLICATION_AUTHORIZATION_TOKEN = 0x8000,
RDM_LG_RQF_HAS_AUTHN_EXTENDED = 0x010000
}
The RDM Login Request Flags.
enum RsslRDMLoginRefreshFlags {
RDM_LG_RFF_NONE = 0x00000000,
RDM_LG_RFF_CLEAR_CACHE = 0x00000001,
RDM_LG_RFF_HAS_ALLOW_SUSPECT_DATA = 0x00000002,
RDM_LG_RFF_HAS_APPLICATION_ID = 0x00000004,
RDM_LG_RFF_HAS_APPLICATION_NAME = 0x00000008,
RDM_LG_RFF_HAS_CONN_CONFIG = 0x00000010,
RDM_LG_RFF_HAS_POSITION = 0x00000020,
RDM_LG_RFF_HAS_PROVIDE_PERM_EXPR = 0x00000040,
RDM_LG_RFF_HAS_PROVIDE_PERM_PROFILE = 0x00000080,
RDM_LG_RFF_HAS_SEQ_NUM = 0x00000100,
RDM_LG_RFF_HAS_SINGLE_OPEN = 0x00000200,
RDM_LG_RFF_HAS_SUPPORT_BATCH = 0x00000400,
RDM_LG_RFF_HAS_SUPPORT_POST = 0x00000800,
RDM_LG_RFF_HAS_SUPPORT_OPT_PAUSE = 0x00001000,
RDM_LG_RFF_HAS_SUPPORT_STANDBY = 0x00002000,
RDM_LG_RFF_HAS_SUPPORT_VIEW = 0x00004000,
RDM_LG_RFF_HAS_USERNAME = 0x00008000,
RDM_LG_RFF_HAS_USERNAME_TYPE = 0x00010000,
RDM_LG_RFF_SOLICITED = 0x00020000,
RDM_LG_RFF_HAS_SUPPORT_ENH_SL = 0x00040000,
RDM_LG_RFF_HAS_SUPPORT_PROV_DIC_DOWNLOAD = 0x00080000,
RDM_LG_RFF_HAS_SEQ_RETRY_INTERVAL = 0x00100000,
RDM_LG_RFF_HAS_UPDATE_BUF_LIMIT = 0x00200000,
RDM_LG_RFF_HAS_SEQ_NUM_RECOVERY = 0x00400000,
RDM_LG_RFF_HAS_AUTHN_TT_REISSUE = 0x00800000,
RDM_LG_RFF_HAS_AUTHN_EXTENDED_RESP = 0x01000000,
RDM_LG_RFF_HAS_AUTHN_ERROR_CODE = 0x02000000,
RDM_LG_RFF_HAS_AUTHN_ERROR_TEXT = 0x04000000
}
The RDM Login Refresh Flags.
enum RsslRDMLoginStatusFlags {
RDM_LG_STF_NONE = 0x00,
RDM_LG_STF_HAS_STATE = 0x01,
RDM_LG_STF_HAS_USERNAME = 0x02,
RDM_LG_STF_HAS_USERNAME_TYPE = 0x04,
RDM_LG_STF_HAS_AUTHN_ERROR_CODE = 0x08,
RDM_LG_STF_HAS_AUTHN_ERROR_TEXT = 0x10
}
The RDM Login Status Flags.
enum RsslRDMLoginConsumerConnectionStatusFlags {
RDM_LG_CCSF_NONE = 0x00,
RDM_LG_CCSF_HAS_WARM_STANDBY_INFO = 0x01
}
The RDM Login Consumer Connection Status Flags.
Functions
RTR_C_INLINE void rsslClearRDMLoginWarmStandbyInfo (RsslRDMLoginWarmStandbyInfo *pInfo)
Clears an RsslRDMLoginWarmStandbyInfo.
RTR_C_INLINE void rsslClearRDMServerInfo (RsslRDMServerInfo *pServerInfo)
Clears an RsslRDMServerInfo.
RTR_C_INLINE void rsslClearRDMLoginRequest (RsslRDMLoginRequest *pRequest)
Clears an RsslRDMLoginRequest.
RTR_C_INLINE RsslRet rsslInitDefaultRDMLoginRequest (RsslRDMLoginRequest *pRequest, RsslInt32 streamId)
Initializes an RsslRDMLoginRequest, clearing it and filling in a typical userName, applicationName and position. NOTE: On Windows it is recommended that rsslInitialize() is called before calling this function to ensure that position is correctly set.
RTR_C_INLINE void rsslClearRDMLoginRefresh (RsslRDMLoginRefresh *pRefresh)
Clears an RsslRDMLoginRefresh.
RTR_C_INLINE void rsslClearRDMLoginClose (RsslRDMLoginClose *pClose)
Clears an RsslRDMLoginClose.
RTR_C_INLINE void rsslClearRDMLoginConsumerConnectionStatus (RsslRDMLoginConsumerConnectionStatus *pConsumerStatus)
Clears an RsslRDMLoginConsumerConnectionStatus.
RTR_C_INLINE void rsslClearRDMLoginStatus (RsslRDMLoginStatus *pStatus)
Clears an RsslRDMLoginStatus.
RTR_C_INLINE void rsslClearRDMLoginMsg (RsslRDMLoginMsg *pLoginMsg)
Clears an RsslRDMLoginMsg.
RSSL_VA_API RsslRet rsslEncodeRDMLoginMsg (RsslEncodeIterator *pEncodeIter, RsslRDMLoginMsg *pLoginMsg, RsslUInt32 *pBytesWritten, RsslErrorInfo *pError)
Encodes an RsslRDMLoginMsg.
RSSL_VA_API RsslRet rsslDecodeRDMLoginMsg (RsslDecodeIterator *pIter, RsslMsg *pMsg, RsslRDMLoginMsg *pLoginMsg, RsslBuffer *pMemoryBuffer, RsslErrorInfo *pError)
Decodes an RsslRDMLoginMsg.
Enumeration Type Documentation
enum RsslRDMLoginConsumerConnectionStatusFlags
See also:
RsslRDMLoginConsumerConnectionStatus, RsslRDMLoginWarmStandbyInfo
Enumerator:
RDM_LG_CCSF_NONE
(0x00) No flags set
RDM_LG_CCSF_HAS_WARM_STANDBY_INFO
(0x01) Indicates presence of Warm Standby information.
enum RsslRDMLoginMsgType
See also:
RsslRDMLoginMsg, RsslRDMMsgBase, RsslRDMLoginRequest, RsslRDMLoginClose, RsslRDMLoginConsumerConnectionStatus, RsslRDMLoginRefresh, RsslRDMLoginStatus
Enumerator:
RDM_LG_MT_UNKNOWN
(0) Unknown
RDM_LG_MT_REQUEST
(1) Login Request
RDM_LG_MT_CLOSE
(2) Login Close
RDM_LG_MT_CONSUMER_CONNECTION_STATUS
(3) Login Consumer Connection Status
RDM_LG_MT_REFRESH
(4) Login Refresh
RDM_LG_MT_STATUS
(5) Login Status
RDM_LG_MT_POST
(6) Indicates an off-stream Post Message.
RDM_LG_MT_ACK
(7) Incidates an off-stream Post Acknowledgement.
enum RsslRDMLoginRefreshFlags
See also:
RsslRDMLoginRefresh
Enumerator:
RDM_LG_RFF_NONE
(0x00000000) No flags set.
RDM_LG_RFF_CLEAR_CACHE
(0x00000001) Indicates whether the receiver of the refresh should clear any associated cache information.
RDM_LG_RFF_HAS_ALLOW_SUSPECT_DATA
(0x00000002) Indicates presence of the allowSuspectData member.
RDM_LG_RFF_HAS_APPLICATION_ID
(0x00000004) Indicates presence of the applicationId member.
RDM_LG_RFF_HAS_APPLICATION_NAME
(0x00000008) Indicates presence of the applicationName member.
RDM_LG_RFF_HAS_CONN_CONFIG
(0x00000010) Indicates presence of the numStandbyServers and serverList members.
RDM_LG_RFF_HAS_POSITION
(0x00000020) Indicates presence of the position member.
RDM_LG_RFF_HAS_PROVIDE_PERM_EXPR
(0x00000040) Indicates presence of the providePermissionExpressions member.
RDM_LG_RFF_HAS_PROVIDE_PERM_PROFILE
(0x00000080) Indicates presence of the providePermissionProfile member.
RDM_LG_RFF_HAS_SEQ_NUM
(0x00000100) Indicates presence of the sequenceNumber member.
RDM_LG_RFF_HAS_SINGLE_OPEN
(0x00000200) Indicates presence of the singleOpen member.
RDM_LG_RFF_HAS_SUPPORT_BATCH
(0x00000400) Indicates presence of the supportBatchRequests member.
RDM_LG_RFF_HAS_SUPPORT_POST
(0x00000800) Indicates presence of the supportOMMPost member.
RDM_LG_RFF_HAS_SUPPORT_OPT_PAUSE
(0x00001000) Indicates presence of the supportOptimizedPauseResume member.
RDM_LG_RFF_HAS_SUPPORT_STANDBY
(0x00002000) Indicates presence of the supportStandby member.
RDM_LG_RFF_HAS_SUPPORT_VIEW
(0x00004000) Indicates presence of the supportViewRequests member.
RDM_LG_RFF_HAS_USERNAME
(0x00008000) Indicates presence of the userName member.
RDM_LG_RFF_HAS_USERNAME_TYPE
(0x00010000) Indicates presence of the userNameType member.
RDM_LG_RFF_SOLICITED
(0x00020000) Indicates whether this refresh is being provided in response to a request.
RDM_LG_RFF_HAS_SUPPORT_ENH_SL
(0x00040000) Indicates presence of the supportEnhancedSymbolList member.
RDM_LG_RFF_HAS_SUPPORT_PROV_DIC_DOWNLOAD
(0x00080000) Indicates presence of the supportProviderDictionaryDownload member.
RDM_LG_RFF_HAS_SEQ_RETRY_INTERVAL
(0x00100000) Indicates presence of the sequenceRetryInterval member.
RDM_LG_RFF_HAS_UPDATE_BUF_LIMIT
(0x00200000) Indicates presence of the updateBufferLimit member.
RDM_LG_RFF_HAS_SEQ_NUM_RECOVERY
(0x00400000) Indicates presence of the sequenceNumberRecovery member.
RDM_LG_RFF_HAS_AUTHN_TT_REISSUE
(0x00800000) Indicates presence of the authentication time to reissue member
RDM_LG_RFF_HAS_AUTHN_EXTENDED_RESP
(0x01000000) Indicates presence of the authentication extended response buffer
RDM_LG_RFF_HAS_AUTHN_ERROR_CODE
(0x02000000) Indicates presence of the authenication error code
RDM_LG_RFF_HAS_AUTHN_ERROR_TEXT
(0x04000000) Indicates presence of the authentication error text member
enum RsslRDMLoginRequestFlags
See also:
RsslRDMLoginRequest
Enumerator:
RDM_LG_RQF_NONE
(0x0000) No flags set
RDM_LG_RQF_HAS_ALLOW_SUSPECT_DATA
(0x0001) Indicates presence of the allowSuspectData member.
RDM_LG_RQF_HAS_APPLICATION_ID
(0x0002) Indicates presence of the applicationId member
RDM_LG_RQF_HAS_APPLICATION_NAME
(0x0004) Indicates presence of the applicationName member
RDM_LG_RQF_HAS_DOWNLOAD_CONN_CONFIG
(0x0008) Indicates presence of the downloadConnectionConfig member
RDM_LG_RQF_HAS_INSTANCE_ID
(0x0010) Indicates presence of the instanceId member
RDM_LG_RQF_HAS_PASSWORD
(0x0020) Indicates presence of the password member
RDM_LG_RQF_HAS_POSITION
(0x0040) Indicates presence of the position member
RDM_LG_RQF_HAS_PROVIDE_PERM_EXPR
(0x0080) Indicates presence of the providePermissionExpressions member
RDM_LG_RQF_HAS_PROVIDE_PERM_PROFILE
(0x0100) Indicates presence of the providePermissionProfile member
RDM_LG_RQF_HAS_ROLE
(0x0200) Indicates presence of the role member
RDM_LG_RQF_HAS_SINGLE_OPEN
(0x0400) Indicates presence of the singleOpen member
RDM_LG_RQF_HAS_USERNAME_TYPE
(0x0800) Indicates presence of the userNameType member
RDM_LG_RQF_NO_REFRESH
(0x1000) Indicates the Consumer or Noninteractive provider does not require a refresh.
RDM_LG_RQF_PAUSE_ALL
(0x2000) Used by a Consumer to request that all open items on a channel be paused. Support for this request is indicated by the supportOptimizedPauseResume member of the RsslRDMLoginRefresh
RDM_LG_RQF_HAS_SUPPORT_PROV_DIC_DOWNLOAD
(0x4000) Indiactes presence of the supportProviderDictionaryDownload member
RDM_LG_RQF_HAS_APPLICATION_AUTHORIZATION_TOKEN
(0x8000) Indicates presence of the applicationAuthenticationToken member
RDM_LG_RQF_HAS_AUTHN_EXTENDED
(0x020000) Indicates presence of extended authentication data.
enum RsslRDMLoginStatusFlags
See also:
RsslRDMLoginStatus
Enumerator:
RDM_LG_STF_NONE
(0x00) No flags set.
RDM_LG_STF_HAS_STATE
(0x01) Indicates presence of the state member.
RDM_LG_STF_HAS_USERNAME
(0x02) Indicates presence of the userName member.
RDM_LG_STF_HAS_USERNAME_TYPE
(0x04) Indicates presence of the userNameType member.
RDM_LG_STF_HAS_AUTHN_ERROR_CODE
(0x08) Indicates presence of the Authentication error code member
RDM_LG_STF_HAS_AUTHN_ERROR_TEXT
(0x10) Indicates presence of the Authentication error text member
enum RsslRDMServerInfoFlags
See also:
RsslRDMServerInfo, RsslRDMLoginRefresh
Enumerator:
RDM_LG_SIF_NONE
(0x00) No flags set
RDM_LG_SIF_HAS_LOAD_FACTOR
(0x01) Indicates presence of the loadFactor member.
RDM_LG_SIF_HAS_TYPE
(0x02) Indicates presence of the serverType member.
Function Documentation
RTR_C_INLINE void rsslClearRDMLoginClose (RsslRDMLoginClose * pClose)
See also:
RsslRDMLoginClose
References RsslRDMMsgBase::domainType, RDM_LG_MT_CLOSE, RsslRDMLoginClose::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, and rsslClearRDMMsgBase().
RTR_C_INLINE void rsslClearRDMLoginConsumerConnectionStatus (RsslRDMLoginConsumerConnectionStatus * pConsumerStatus)
See also:
RsslRDMLoginConsumerConnectionStatus
References RsslRDMMsgBase::domainType, RsslRDMLoginConsumerConnectionStatus::flags, RDM_LG_CCSF_NONE, RDM_LG_MT_CONSUMER_CONNECTION_STATUS, RsslRDMLoginConsumerConnectionStatus::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMLoginWarmStandbyInfo(), rsslClearRDMMsgBase(), and RsslRDMLoginConsumerConnectionStatus::warmStandbyInfo.
RTR_C_INLINE void rsslClearRDMLoginMsg (RsslRDMLoginMsg * pLoginMsg)
See also:
RsslRDMLoginMsg
References RsslRDMMsgBase::domainType, and RsslRDMLoginMsg::rdmMsgBase.
RTR_C_INLINE void rsslClearRDMLoginRefresh (RsslRDMLoginRefresh * pRefresh)
See also:
RsslRDMLoginRefresh
References RsslRDMLoginRefresh::allowSuspectData, RsslRDMLoginRefresh::applicationId, RsslRDMLoginRefresh::applicationName, RsslRDMLoginRefresh::authenticationErrorCode, RsslRDMLoginRefresh::authenticationErrorText, RsslRDMLoginRefresh::authenticationExtendedResp, RsslRDMLoginRefresh::authenticationTTReissue, RsslRDMMsgBase::domainType, RsslRDMLoginRefresh::flags, RsslRDMLoginRefresh::numStandbyServers, RsslRDMLoginRefresh::position, RsslRDMLoginRefresh::providePermissionExpressions, RsslRDMLoginRefresh::providePermissionProfile, RDM_LG_MT_REFRESH, RDM_LG_RFF_NONE, RsslRDMLoginRefresh::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMLoginRefresh::sequenceNumber, RsslRDMLoginRefresh::sequenceNumberRecovery, RsslRDMLoginRefresh::sequenceRetryInterval, RsslRDMLoginRefresh::serverCount, RsslRDMLoginRefresh::serverList, RsslRDMLoginRefresh::singleOpen, RsslRDMLoginRefresh::state, RsslRDMLoginRefresh::supportBatchRequests, RsslRDMLoginRefresh::supportEnhancedSymbolList, RsslRDMLoginRefresh::supportOMMPost, RsslRDMLoginRefresh::supportOptimizedPauseResume, RsslRDMLoginRefresh::supportProviderDictionaryDownload, RsslRDMLoginRefresh::supportStandby, RsslRDMLoginRefresh::supportViewRequests, RsslRDMLoginRefresh::updateBufferLimit, RsslRDMLoginRefresh::userName, and RsslRDMLoginRefresh::userNameType.
RTR_C_INLINE void rsslClearRDMLoginRequest (RsslRDMLoginRequest * pRequest)
See also:
RsslRDMLoginRequest, rsslInitDefaultRDMLoginRequest
References RsslRDMLoginRequest::allowSuspectData, RsslRDMLoginRequest::applicationAuthorizationToken, RsslRDMLoginRequest::applicationId, RsslRDMLoginRequest::applicationName, RsslRDMLoginRequest::authenticationExtended, RsslRDMMsgBase::domainType, RsslRDMLoginRequest::downloadConnectionConfig, RsslRDMLoginRequest::flags, RsslRDMLoginRequest::instanceId, RsslRDMLoginRequest::password, RsslRDMLoginRequest::position, RsslRDMLoginRequest::providePermissionExpressions, RsslRDMLoginRequest::providePermissionProfile, RDM_LG_MT_REQUEST, RDM_LG_RQF_NONE, RsslRDMLoginRequest::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, RsslRDMLoginRequest::role, rsslClearRDMMsgBase(), RsslRDMLoginRequest::singleOpen, RsslRDMLoginRequest::supportProviderDictionaryDownload, RsslRDMLoginRequest::userName, and RsslRDMLoginRequest::userNameType.
Referenced by rsslInitDefaultRDMLoginRequest().
RTR_C_INLINE void rsslClearRDMLoginStatus (RsslRDMLoginStatus * pStatus)
See also:
RsslRDMLoginStatus
References RsslRDMLoginStatus::authenticationErrorCode, RsslRDMLoginStatus::authenticationErrorText, RsslRDMMsgBase::domainType, RsslRDMLoginStatus::flags, RDM_LG_MT_STATUS, RDM_LG_STF_NONE, RsslRDMLoginStatus::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMLoginStatus::state, RsslRDMLoginStatus::userName, and RsslRDMLoginStatus::userNameType.
RTR_C_INLINE void rsslClearRDMLoginWarmStandbyInfo (RsslRDMLoginWarmStandbyInfo * pInfo)
See also:
RsslRDMLoginWarmStandbyInfo, RsslRDMLoginConsumerConnectionStatus
References RsslRDMLoginWarmStandbyInfo::action, and RsslRDMLoginWarmStandbyInfo::warmStandbyMode.
Referenced by rsslClearRDMLoginConsumerConnectionStatus().
RTR_C_INLINE void rsslClearRDMServerInfo (RsslRDMServerInfo * pServerInfo)
See also:
RsslRDMServerInfo
References RsslRDMServerInfo::flags, RsslRDMServerInfo::hostname, RsslRDMServerInfo::loadFactor, RsslRDMServerInfo::port, RDM_LG_SIF_NONE, RsslRDMServerInfo::serverIndex, and RsslRDMServerInfo::serverType.
RSSL_VA_API RsslRet rsslDecodeRDMLoginMsg (RsslDecodeIterator * pIter, RsslMsg * pMsg, RsslRDMLoginMsg * pLoginMsg, RsslBuffer * pMemoryBuffer, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Decode Iterator
pLoginMsg The RDM Login Message to be populated
pMemoryBuffer An RsslBuffer pointing to space that may be used as additional storage space for the decoded message.
pError An Error Structure, which will be populated if the decoding fails.
Returns:
RSSL_RET_SUCCESS, if the message was succesfully decoded and correctly followed the RDM.
RSSL_RET_FAILURE, if the message was not successfully decoded or did follow the RDM. Information about the error will be stored in pError.
RSSL_RET_BUFFER_TOO_SMALL, if the size of pNewMemoryBuffer was not large enough to store all additional data.
See also:
RsslRDMLoginMsg
Referenced by rsslDecodeRDMMsg().
RSSL_VA_API RsslRet rsslEncodeRDMLoginMsg (RsslEncodeIterator * pEncodeIter, RsslRDMLoginMsg * pLoginMsg, RsslUInt32 * pBytesWritten, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Encode Iterator
pLoginMsg The RDM Login Message to Encode
pBytesWritten Returns the total number of bytes used to encode the message.
See also:
RsslRDMLoginMsg
Referenced by rsslEncodeRDMMsg().
RTR_C_INLINE RsslRet rsslInitDefaultRDMLoginRequest (RsslRDMLoginRequest * pRequest, RsslInt32 streamId)
See also:
RsslRDMLoginRequest, rsslInitDefaultRDMLoginRequest
References RsslRDMLoginRequest::applicationId, RsslRDMLoginRequest::applicationName, RsslRDMLoginRequest::defaultPosition, RsslRDMLoginRequest::defaultUsername, RsslRDMLoginRequest::flags, RsslRDMLoginRequest::position, RDM_LG_RQF_HAS_APPLICATION_ID, RDM_LG_RQF_HAS_APPLICATION_NAME, RDM_LG_RQF_HAS_POSITION, RsslRDMLoginRequest::rdmMsgBase, rsslClearRDMLoginRequest(), RsslRDMMsgBase::streamId, and RsslRDMLoginRequest::userName.