Transport API Value Addded Components Reference Manual: RSSL RDM Directory Codec
RSSL RDM Directory Codec
RSSL RDM Codec API
The RSSL RDM Directory component is intended to assist developers with encoding and decoding messages used by the Directory Reuters Domain Model. This component provides typed data structures, encoding and decoding functions for Directory Domain messages.
Data Structures
struct RsslRDMConsumerStatusService
Information about how a Consumer is using a particular service with regard to Source Mirroring.
struct RsslRDMServiceInfo
The RDM Service Info. Contains information provided by the Source Directory Info filter.
struct RsslRDMAddressPortInfo
The Address Port Info. Contains Host Address and Port information.
struct RsslRDMMCAddressPortInfo
The MC Address Port Info. Contains Host Address Port and domain information.
struct RsslRDMServiceSeqMCastInfo
The RDM Sequenced Multicast Info. Contains information provided by the Source Directory Sequenced Multicast filter.
struct RsslRDMServiceState
The RDM Service State. Contains information provided by the Source Directory State filter.
struct RsslRDMServiceGroupState
The RDM Service Group State. Contains information provided by the Source Directory Group filter.
struct RsslRDMServiceLoad
The RDM Service Load. Contains information provided by the Source Directory Load filter.
struct RsslRDMServiceData
The RDM Service Data. Contains information provided by the Source Directory Data filter.
struct RsslRDMServiceLink
The RDM Service Link. Contains information about an upstream source associated with the service.
struct RsslRDMServiceLinkInfo
The RDM Service Link Info. Contains information provided by the Source Directory Link filter.
struct RsslRDMService
The RDM Service. Contains information about a particular service.
struct RsslRDMDirectoryRequest
The RDM Directory Request. Used by an OMM Consumer to request Source Directory information from an OMM Provider.
struct RsslRDMDirectoryRefresh
The RDM Directory Refresh. Used by an OMM Provider to provide information about available services.
struct RsslRDMDirectoryUpdate
The RDM Directory Update. Used by an OMM Provider to provide updates about available services.
struct RsslRDMDirectoryClose
The RDM Directory Close. Used by an OMM Consumer to close an open Source Directory stream.
struct RsslRDMDirectoryStatus
The RDM Directory Status. Used by an OMM Provider to indicate changes to the Directory stream.
struct RsslRDMDirectoryConsumerStatus
The RDM Directory Consumer Status. Used by an OMM Consumer to send Source Mirroring information.
union RsslRDMDirectoryMsg
The RDM Directory Msg. The Directory Message encoder and decoder functions expect this type. It is a group of the classes of message that the Directory domain supports. Any specific message class may be cast to an RsslRDMDirectoryMsg, and an RsslRDMDirectoryMsg may be cast to any specific message class. The RsslRDMMsgBase contains members common to each class that may be used to identify the class of message.
Modules
RDM Directory Helper Functions
Enumerations
enum RsslRDMServiceInfoFlags {
RDM_SVC_IFF_NONE = 0x000,
RDM_SVC_IFF_HAS_VENDOR = 0x001,
RDM_SVC_IFF_HAS_IS_SOURCE = 0x002,
RDM_SVC_IFF_HAS_DICTS_PROVIDED = 0x004,
RDM_SVC_IFF_HAS_DICTS_USED = 0x008,
RDM_SVC_IFF_HAS_QOS = 0x010,
RDM_SVC_IFF_HAS_SUPPORT_QOS_RANGE = 0x020,
RDM_SVC_IFF_HAS_ITEM_LIST = 0x040,
RDM_SVC_IFF_HAS_SUPPORT_OOB_SNAPSHOTS = 0x080,
RDM_SVC_IFF_HAS_ACCEPTING_CONS_STATUS = 0x100
}
The RDM Service Info flags.
enum RsslRDMSeqMCastInfoFlags {
RDM_SVC_SMF_NONE = 0x000,
RDM_SVC_SMF_HAS_SNAPSHOT_SERV = 0x001,
RDM_SVC_SMF_HAS_GAP_REC_SERV = 0x002,
RDM_SVC_SMF_HAS_REF_DATA_SERV = 0x004,
RDM_SVC_SMF_HAS_SMC_SERV = 0x008,
RDM_SVC_SMF_HAS_GMC_SERV = 0x010
}
The RDM Sequenced MCast Info flags.
enum RsslRDMServiceStateFlags {
RDM_SVC_STF_NONE = 0x00,
RDM_SVC_STF_HAS_ACCEPTING_REQS = 0x01,
RDM_SVC_STF_HAS_STATUS = 0x02
}
The RDM Service State flags.
enum RsslRDMServiceGroupFlags {
RDM_SVC_GRF_NONE = 0x00,
RDM_SVC_GRF_HAS_MERGED_TO_GROUP = 0x01,
RDM_SVC_GRF_HAS_STATUS = 0x02
}
The RDM Service Group State flags.
enum RsslRDMServiceLoadFlags {
RDM_SVC_LDF_NONE = 0x00,
RDM_SVC_LDF_HAS_OPEN_LIMIT = 0x01,
RDM_SVC_LDF_HAS_OPEN_WINDOW = 0x02,
RDM_SVC_LDF_HAS_LOAD_FACTOR = 0x04
}
The RDM Service Load flags.
enum RsslRDMServiceDataFlags {
RDM_SVC_DTF_NONE = 0x00,
RDM_SVC_DTF_HAS_DATA = 0x01
}
The RDM Service Data flags.
enum RsslRDMServiceLinkFlags {
RDM_SVC_LKF_NONE = 0x00,
RDM_SVC_LKF_HAS_TYPE = 0x01,
RDM_SVC_LKF_HAS_CODE = 0x02,
RDM_SVC_LKF_HAS_TEXT = 0x04
}
The RDM Service Link flags.
enum RsslRDMServiceFlags {
RDM_SVCF_NONE = 0x00,
RDM_SVCF_HAS_INFO = 0x01,
RDM_SVCF_HAS_STATE = 0x02,
RDM_SVCF_HAS_LOAD = 0x04,
RDM_SVCF_HAS_DATA = 0x08,
RDM_SVCF_HAS_LINK = 0x10,
RDM_SVCF_HAS_SEQ_MCAST = 0x20
}
The RDM Service flags.
enum RsslRDMDirectoryMsgType {
RDM_DR_MT_UNKNOWN = 0,
RDM_DR_MT_REQUEST = 1,
RDM_DR_MT_CLOSE = 2,
RDM_DR_MT_CONSUMER_STATUS = 3,
RDM_DR_MT_REFRESH = 4,
RDM_DR_MT_UPDATE = 5,
RDM_DR_MT_STATUS = 6
}
The types of RDM Directory Messages. When the rdmMsgBase's domainType is RSSL_DMT_SOURCE, the rdmMsgType member may be set to one of these to indicate the specific RsslRDMDirectoryMsg class.
enum RsslRDMDirectoryRequestFlags {
RDM_DR_RQF_NONE = 0x00,
RDM_DR_RQF_HAS_SERVICE_ID = 0x01,
RDM_DR_RQF_STREAMING = 0x02
}
The RDM Directory Request Flags.
enum RsslRDMDirectoryRefreshFlags {
RDM_DR_RFF_NONE = 0x00,
RDM_DR_RFF_HAS_SERVICE_ID = 0x01,
RDM_DR_RFF_SOLICITED = 0x02,
RDM_DR_RFF_HAS_SEQ_NUM = 0x04,
RDM_DR_RFF_CLEAR_CACHE = 0x08
}
The RDM Directory Refresh Flags.
enum RsslRDMDirectoryUpdateFlags {
RDM_DR_UPF_NONE = 0x00,
RDM_DR_UPF_HAS_SERVICE_ID = 0x01,
RDM_DR_UPF_HAS_FILTER = 0x02,
RDM_DR_UPF_HAS_SEQ_NUM = 0x04
}
The RDM Directory Update Flags.
enum RsslRDMDirectoryStatusFlags {
RDM_DR_STF_NONE = 0x00,
RDM_DR_STF_HAS_FILTER = 0x01,
RDM_DR_STF_HAS_SERVICE_ID = 0x02,
RDM_DR_STF_HAS_STATE = 0x04,
RDM_DR_STF_CLEAR_CACHE = 0x08
}
The RDM Directory Status Flags.
Functions
RTR_C_INLINE void rsslClearRDMConsumerStatusService (RsslRDMConsumerStatusService *pStatus)
Clears an RsslRDMConsumerStatusService.
RTR_C_INLINE void rsslClearRDMAddressPortInfo (RsslRDMAddressPortInfo *pAddressPortInfo)
Clears an RsslRDMAddressPortInfo.
RTR_C_INLINE void rsslClearRDMMCAddressPortInfo (RsslRDMMCAddressPortInfo *pAddressPortInfo)
Clears an RsslRDMMCAddressPortInfo.
RTR_C_INLINE void rsslClearRDMServiceSeqMCastInfo (RsslRDMServiceSeqMCastInfo *pSeqMCastInfo)
Clears an RsslRDMServiceSeqMCastInfo.
RTR_C_INLINE void rsslClearRDMServiceInfo (RsslRDMServiceInfo *pServiceInfo)
Clears an RsslRDMServiceInfo.
RTR_C_INLINE void rsslClearRDMServiceState (RsslRDMServiceState *pServiceState)
Clears an RsslRDMServiceState.
RTR_C_INLINE void rsslClearRDMServiceGroupState (RsslRDMServiceGroupState *pGroupState)
Clears an RsslRDMServiceGroupState.
RTR_C_INLINE void rsslClearRDMServiceLoad (RsslRDMServiceLoad *pServiceLoad)
Clears an RsslRDMServiceLoad.
RTR_C_INLINE void rsslClearRDMServiceData (RsslRDMServiceData *pServiceData)
Clears an RsslRDMServiceData.
RTR_C_INLINE void rsslClearRDMServiceLink (RsslRDMServiceLink *pServiceLink)
Clears an RsslRDMServiceLink.
RTR_C_INLINE void rsslClearRDMServiceLinkInfo (RsslRDMServiceLinkInfo *pInfo)
Clears an RsslRDMServiceLinkInfo.
RTR_C_INLINE void rsslClearRDMService (RsslRDMService *pService)
Clears an RsslRDMService.
RTR_C_INLINE void rsslClearRDMDirectoryRequest (RsslRDMDirectoryRequest *pRequest)
Clears an RsslRDMDirectoryRequest.
RTR_C_INLINE void rsslClearRDMDirectoryRefresh (RsslRDMDirectoryRefresh *pRefresh)
Clears an RsslRDMDirectoryRefresh.
RTR_C_INLINE void rsslClearRDMDirectoryUpdate (RsslRDMDirectoryUpdate *pUpdate)
Clears an RsslRDMDirectoryUpdate.
RTR_C_INLINE RsslRet rsslInitDefaultRDMDirectoryRequest (RsslRDMDirectoryRequest *pRequest, RsslInt32 streamId)
Initializes an RsslRDMDirectoryRequest, clearing it and filling in a typical filter setting of RDM_DIRECTORY_SERVICE_INFO_FILTER, RDM_DIRECTORY_SERVICE_STATE_FILTER, and RDM_DIRECTORY_SERVICE_GROUP_FILTER.
RTR_C_INLINE void rsslClearRDMDirectoryClose (RsslRDMDirectoryClose *pClose)
Clears an RsslRDMDirectoryClose.
RTR_C_INLINE void rsslClearRDMDirectoryStatus (RsslRDMDirectoryStatus *pStatus)
The RDM Directory Status. Used by an OMM Provider to indicate changes to the Directory stream.
RTR_C_INLINE void rsslClearRDMDirectoryConsumerStatus (RsslRDMDirectoryConsumerStatus *pConsumerStatus)
Clears an RsslRDMDirectoryConsumerStatus.
RTR_C_INLINE void rsslClearRDMDirectoryMsg (RsslRDMDirectoryMsg *pMsg)
Clears an RsslRDMDirectoryMsg.
RSSL_VA_API RsslRet rsslEncodeRDMDirectoryMsg (RsslEncodeIterator *pEncodeIter, RsslRDMDirectoryMsg *pDirectoryMsg, RsslUInt32 *pBytesWritten, RsslErrorInfo *pError)
Encodes an RsslRDMDirectoryMsg.
RSSL_VA_API RsslRet rsslDecodeRDMDirectoryMsg (RsslDecodeIterator *pIter, RsslMsg *pMsg, RsslRDMDirectoryMsg *pDirectoryMsg, RsslBuffer *pMemoryBuffer, RsslErrorInfo *pError)
Decodes an RsslRDMDirectoryMsg.
Enumeration Type Documentation
enum RsslRDMDirectoryMsgType
See also:
RsslRDMDirectoryMsg, RsslRDMMsgBase, RsslRDMDirectoryRequest, RsslRDMDirectoryClose, RsslRDMDirectoryConsumerStatus, RsslRDMDirectoryRefresh, RsslRDMDirectoryStatus
Enumerator:
RDM_DR_MT_UNKNOWN
(0) Unknown
RDM_DR_MT_REQUEST
(1) Directory Request
RDM_DR_MT_CLOSE
(2) Directory Close
RDM_DR_MT_CONSUMER_STATUS
(3) Directory Consumer Status
RDM_DR_MT_REFRESH
(4) Directory Refresh
RDM_DR_MT_UPDATE
(5) Directory Update
RDM_DR_MT_STATUS
(6) Directory Status
enum RsslRDMDirectoryRefreshFlags
See also:
RsslRDMDirectoryRefresh
Enumerator:
RDM_DR_RFF_NONE
(0x00) No flags set.
RDM_DR_RFF_HAS_SERVICE_ID
(0x01) Indicates presence of the serviceId member.
RDM_DR_RFF_SOLICITED
(0x02) Indicates whether this Refresh is provided in response to a request.
RDM_DR_RFF_HAS_SEQ_NUM
(0x04) Indicates presence of the sequenceNumber.
RDM_DR_RFF_CLEAR_CACHE
(0x08) Indicates whether the Consumer should clear any existing cached service information.
enum RsslRDMDirectoryRequestFlags
See also:
RsslRDMDirectoryRequest
Enumerator:
RDM_DR_RQF_NONE
(0x00) No flags set.
RDM_DR_RQF_HAS_SERVICE_ID
(0x01) Indicates presence of the serviceId member.
RDM_DR_RQF_STREAMING
(0x02) Indicates whether the request is a streaming request, i.e. whether updates about source directory information are desired.
enum RsslRDMDirectoryStatusFlags
See also:
RsslRDMDirectoryStatus
Enumerator:
RDM_DR_STF_NONE
(0x00) No flags set.
RDM_DR_STF_HAS_FILTER
(0x01) Indicates presence of the filter member.
RDM_DR_STF_HAS_SERVICE_ID
(0x02) Indicates presence of the serviceId member.
RDM_DR_STF_HAS_STATE
(0x04) Indicates presence of the state member.
RDM_DR_STF_CLEAR_CACHE
(0x08) Indicates whether the Consumer should clear any existing cached service information.
enum RsslRDMDirectoryUpdateFlags
See also:
RsslRDMDirectoryUpdate
Enumerator:
RDM_DR_UPF_NONE
(0x00) No flags set.
RDM_DR_UPF_HAS_SERVICE_ID
(0x01) Indicates presence of the serviceId member.
RDM_DR_UPF_HAS_FILTER
(0x02) Indicates presence of the filter member.
RDM_DR_UPF_HAS_SEQ_NUM
(0x04) Indicates presence of the sequenceNumber member.
enum RsslRDMSeqMCastInfoFlags
See also:
RsslRDMSeqMCastInfo
Enumerator:
RDM_SVC_SMF_NONE
(0x000) No flags set.
RDM_SVC_SMF_HAS_SNAPSHOT_SERV
(0x001) Indicates presence of Snapshot Server Info
RDM_SVC_SMF_HAS_GAP_REC_SERV
(0x002) Indicates presence of Gap Recovery Server Info
RDM_SVC_SMF_HAS_REF_DATA_SERV
(0x004) Indicates presence of Reference Data Server Info
RDM_SVC_SMF_HAS_SMC_SERV
(0x008) Indicates presence of Streaming Multicast Channels Server Info
RDM_SVC_SMF_HAS_GMC_SERV
(0x010) Indicates presence of Gap Multicast Channel Server Info
enum RsslRDMServiceDataFlags
See also:
RsslRDMServiceData
Enumerator:
RDM_SVC_DTF_NONE
(0x00) No flags set.
RDM_SVC_DTF_HAS_DATA
(0x01) Indicates presence of the type, dataType and data members.
enum RsslRDMServiceFlags
See also:
RsslRDMService
Enumerator:
RDM_SVCF_NONE
(0x00) No flags set.
RDM_SVCF_HAS_INFO
(0x01) Indicates presence of the info member.
RDM_SVCF_HAS_STATE
(0x02) Indicates presence of the state member.
RDM_SVCF_HAS_LOAD
(0x04) Indicates presence of the load member.
RDM_SVCF_HAS_DATA
(0x08) Indicates presence of the data member.
RDM_SVCF_HAS_LINK
(0x10) Indicates presence of the linkInfo member.
RDM_SVCF_HAS_SEQ_MCAST
(0x20) Indiacted presence of the sequenced multicast member.
enum RsslRDMServiceGroupFlags
See also:
RsslRDMServiceGroupState
Enumerator:
RDM_SVC_GRF_NONE
(0x00) No flags set.
RDM_SVC_GRF_HAS_MERGED_TO_GROUP
(0x01) Indicates presence of the mergedToGroup member.
RDM_SVC_GRF_HAS_STATUS
(0x02) Indicates presence of the status member.
enum RsslRDMServiceInfoFlags
See also:
RsslRDMServiceInfo
Enumerator:
RDM_SVC_IFF_NONE
(0x000) No flags set.
RDM_SVC_IFF_HAS_VENDOR
(0x001) Indicates presence of the vendor member.
RDM_SVC_IFF_HAS_IS_SOURCE
(0x002) Indicates presence of the isSource member.
RDM_SVC_IFF_HAS_DICTS_PROVIDED
(0x004) Indicates presence of the dictionariesProvidedList member.
RDM_SVC_IFF_HAS_DICTS_USED
(0x008) Indicates presence of the dictionariesUsedList member.
RDM_SVC_IFF_HAS_QOS
(0x010) Indicates presence of the qosList member.
RDM_SVC_IFF_HAS_SUPPORT_QOS_RANGE
(0x020) Indicates presence of the supportsQosRange member.
RDM_SVC_IFF_HAS_ITEM_LIST
(0x040) Indicates presence of the itemList member.
RDM_SVC_IFF_HAS_SUPPORT_OOB_SNAPSHOTS
(0x080) Indicates presence of the supportsOutOfBandSnapshots member.
RDM_SVC_IFF_HAS_ACCEPTING_CONS_STATUS
(0x100) Indicates presence of the acceptingConsumerStatus member.
enum RsslRDMServiceLinkFlags
See also:
RsslRDMServiceLink
Enumerator:
RDM_SVC_LKF_NONE
(0x00) No flags set.
RDM_SVC_LKF_HAS_TYPE
(0x01) Indicates presence of the source type.
RDM_SVC_LKF_HAS_CODE
(0x02) Indicates presence of the link code.
RDM_SVC_LKF_HAS_TEXT
(0x04) Indcates presence of link text.
enum RsslRDMServiceLoadFlags
See also:
RsslRDMServiceLoad
Enumerator:
RDM_SVC_LDF_NONE
(0x00) No flags set.
RDM_SVC_LDF_HAS_OPEN_LIMIT
(0x01) Indicates presence of an open limit on the service.
RDM_SVC_LDF_HAS_OPEN_WINDOW
(0x02) Indicates presence of an open window on the service.
RDM_SVC_LDF_HAS_LOAD_FACTOR
(0x04) Indicates presence of a load factor.
enum RsslRDMServiceStateFlags
See also:
RsslRDMServiceState
Enumerator:
RDM_SVC_STF_NONE
(0x00) No flags set.
RDM_SVC_STF_HAS_ACCEPTING_REQS
(0x01) Indicates presence of the acceptingRequests member.
RDM_SVC_STF_HAS_STATUS
(0x02) Indicates presence of the status member.
Function Documentation
RTR_C_INLINE void rsslClearRDMAddressPortInfo (RsslRDMAddressPortInfo * pAddressPortInfo)
See also:
RsslRDMAddressPortInfo
References RsslRDMAddressPortInfo::address, and RsslRDMAddressPortInfo::port.
Referenced by rsslClearRDMServiceSeqMCastInfo().
RTR_C_INLINE void rsslClearRDMConsumerStatusService (RsslRDMConsumerStatusService * pStatus)
See also:
RsslRDMConsumerStatusService
References RsslRDMConsumerStatusService::action, RsslRDMConsumerStatusService::serviceId, and RsslRDMConsumerStatusService::sourceMirroringMode.
RTR_C_INLINE void rsslClearRDMDirectoryClose (RsslRDMDirectoryClose * pClose)
See also:
RsslRDMDirectoryClose
References RsslRDMMsgBase::domainType, RDM_DR_MT_CLOSE, RsslRDMDirectoryClose::rdmMsgBase, and RsslRDMMsgBase::rdmMsgType.
RTR_C_INLINE void rsslClearRDMDirectoryConsumerStatus (RsslRDMDirectoryConsumerStatus * pConsumerStatus)
See also:
RsslRDMDirectoryConsumerStatus
References RsslRDMDirectoryConsumerStatus::consumerServiceStatusCount, RsslRDMDirectoryConsumerStatus::consumerServiceStatusList, RsslRDMMsgBase::domainType, RDM_DR_MT_CONSUMER_STATUS, RsslRDMDirectoryConsumerStatus::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, and rsslClearRDMMsgBase().
RTR_C_INLINE void rsslClearRDMDirectoryMsg (RsslRDMDirectoryMsg * pMsg)
See also:
RsslRDMDirectoryMsg
References RsslRDMMsgBase::domainType, and RsslRDMDirectoryMsg::rdmMsgBase.
RTR_C_INLINE void rsslClearRDMDirectoryRefresh (RsslRDMDirectoryRefresh * pRefresh)
See also:
RsslRDMDirectoryRefresh
References RsslRDMMsgBase::domainType, RsslRDMDirectoryRefresh::filter, RsslRDMDirectoryRefresh::flags, RDM_DR_MT_REFRESH, RDM_DR_RFF_NONE, RsslRDMDirectoryRefresh::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMDirectoryRefresh::sequenceNumber, RsslRDMDirectoryRefresh::serviceCount, RsslRDMDirectoryRefresh::serviceId, RsslRDMDirectoryRefresh::serviceList, and RsslRDMDirectoryRefresh::state.
RTR_C_INLINE void rsslClearRDMDirectoryRequest (RsslRDMDirectoryRequest * pRequest)
See also:
RsslRDMDirectoryRequest, rsslInitDefaultRDMDirectoryRequest
References RsslRDMMsgBase::domainType, RsslRDMDirectoryRequest::filter, RsslRDMDirectoryRequest::flags, RDM_DR_MT_REQUEST, RDM_DR_RQF_NONE, RsslRDMDirectoryRequest::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), and RsslRDMDirectoryRequest::serviceId.
Referenced by rsslInitDefaultRDMDirectoryRequest().
RTR_C_INLINE void rsslClearRDMDirectoryStatus (RsslRDMDirectoryStatus * pStatus)
See also:
RsslRDMMsgBase, RsslRDMMsg, rsslClearRDMDirectoryStatus
References RsslRDMMsgBase::domainType, RsslRDMDirectoryStatus::filter, RsslRDMDirectoryStatus::flags, RDM_DR_MT_STATUS, RDM_DR_STF_NONE, RsslRDMDirectoryStatus::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMDirectoryStatus::serviceId, and RsslRDMDirectoryStatus::state.
RTR_C_INLINE void rsslClearRDMDirectoryUpdate (RsslRDMDirectoryUpdate * pUpdate)
See also:
RsslRDMDirectoryUpdate
References RsslRDMMsgBase::domainType, RsslRDMDirectoryUpdate::filter, RsslRDMDirectoryUpdate::flags, RDM_DR_MT_UPDATE, RDM_DR_UPF_NONE, RsslRDMDirectoryUpdate::rdmMsgBase, RsslRDMMsgBase::rdmMsgType, rsslClearRDMMsgBase(), RsslRDMDirectoryUpdate::sequenceNumber, RsslRDMDirectoryUpdate::serviceCount, RsslRDMDirectoryUpdate::serviceId, and RsslRDMDirectoryUpdate::serviceList.
RTR_C_INLINE void rsslClearRDMMCAddressPortInfo (RsslRDMMCAddressPortInfo * pAddressPortInfo)
*
See also:
RsslRDMMCAddressPortInfo
References RsslRDMMCAddressPortInfo::address, RsslRDMMCAddressPortInfo::domain, and RsslRDMMCAddressPortInfo::port.
RTR_C_INLINE void rsslClearRDMService (RsslRDMService * pService)
See also:
RsslRDMService
References RsslRDMService::action, RsslRDMService::data, RsslRDMService::flags, RsslRDMService::groupStateCount, RsslRDMService::groupStateList, RsslRDMService::info, RsslRDMService::linkInfo, RsslRDMService::load, RDM_SVCF_NONE, rsslClearRDMServiceData(), rsslClearRDMServiceInfo(), rsslClearRDMServiceLinkInfo(), rsslClearRDMServiceLoad(), rsslClearRDMServiceSeqMCastInfo(), rsslClearRDMServiceState(), RsslRDMService::seqMCastInfo, RsslRDMService::serviceId, and RsslRDMService::state.
RTR_C_INLINE void rsslClearRDMServiceData (RsslRDMServiceData * pServiceData)
See also:
RsslRDMServiceData
References RsslRDMServiceData::action, RsslRDMServiceData::data, RsslRDMServiceData::dataType, RsslRDMServiceData::flags, RDM_SVC_DTF_NONE, and RsslRDMServiceData::type.
Referenced by rsslClearRDMService().
RTR_C_INLINE void rsslClearRDMServiceGroupState (RsslRDMServiceGroupState * pGroupState)
See also:
RsslRDMServiceGroupState
References RsslRDMServiceGroupState::action, RsslRDMServiceGroupState::flags, RsslRDMServiceGroupState::group, RsslRDMServiceGroupState::mergedToGroup, RDM_SVC_GRF_NONE, and RsslRDMServiceGroupState::status.
RTR_C_INLINE void rsslClearRDMServiceInfo (RsslRDMServiceInfo * pServiceInfo)
See also:
RsslRDMServiceInfo
References RsslRDMServiceInfo::acceptingConsumerStatus, RsslRDMServiceInfo::action, RsslRDMServiceInfo::capabilitiesCount, RsslRDMServiceInfo::capabilitiesList, RsslRDMServiceInfo::dictionariesProvidedCount, RsslRDMServiceInfo::dictionariesProvidedList, RsslRDMServiceInfo::dictionariesUsedCount, RsslRDMServiceInfo::dictionariesUsedList, RsslRDMServiceInfo::flags, RsslRDMServiceInfo::isSource, RsslRDMServiceInfo::itemList, RsslRDMServiceInfo::qosCount, RsslRDMServiceInfo::qosList, RDM_SVC_IFF_NONE, RsslRDMServiceInfo::serviceName, RsslRDMServiceInfo::supportsOutOfBandSnapshots, RsslRDMServiceInfo::supportsQosRange, and RsslRDMServiceInfo::vendor.
Referenced by rsslClearRDMService().
RTR_C_INLINE void rsslClearRDMServiceLink (RsslRDMServiceLink * pServiceLink)
See also:
RsslRDMServiceLink
References RsslRDMServiceLink::action, RsslRDMServiceLink::flags, RsslRDMServiceLink::linkCode, RsslRDMServiceLink::linkState, RsslRDMServiceLink::name, RDM_SVC_LKF_NONE, RsslRDMServiceLink::text, and RsslRDMServiceLink::type.
RTR_C_INLINE void rsslClearRDMServiceLinkInfo (RsslRDMServiceLinkInfo * pInfo)
See also:
RsslRDMServiceLinkInfo
References RsslRDMServiceLinkInfo::action, RsslRDMServiceLinkInfo::linkCount, and RsslRDMServiceLinkInfo::linkList.
Referenced by rsslClearRDMService().
RTR_C_INLINE void rsslClearRDMServiceLoad (RsslRDMServiceLoad * pServiceLoad)
See also:
RsslRDMServiceLoad
References RsslRDMServiceLoad::action, RsslRDMServiceLoad::flags, RsslRDMServiceLoad::loadFactor, RsslRDMServiceLoad::openLimit, RsslRDMServiceLoad::openWindow, and RDM_SVC_LDF_NONE.
Referenced by rsslClearRDMService().
RTR_C_INLINE void rsslClearRDMServiceSeqMCastInfo (RsslRDMServiceSeqMCastInfo * pSeqMCastInfo)
See also:
RsslRDMServiceSeqMCastInfo
References RsslRDMServiceSeqMCastInfo::action, RsslRDMServiceSeqMCastInfo::flags, RsslRDMServiceSeqMCastInfo::GapMCastChanServerCount, RsslRDMServiceSeqMCastInfo::GapMCastChanServerList, RsslRDMServiceSeqMCastInfo::gapRecoveryServer, RDM_SVC_SMF_NONE, RsslRDMServiceSeqMCastInfo::refDataServer, rsslClearRDMAddressPortInfo(), RsslRDMServiceSeqMCastInfo::snapshotServer, RsslRDMServiceSeqMCastInfo::StreamingMCastChanServerCount, and RsslRDMServiceSeqMCastInfo::StreamingMCastChanServerList.
Referenced by rsslClearRDMService().
RTR_C_INLINE void rsslClearRDMServiceState (RsslRDMServiceState * pServiceState)
See also:
RsslRDMServiceState
References RsslRDMServiceState::acceptingRequests, RsslRDMServiceState::action, RsslRDMServiceState::flags, RDM_SVC_STF_NONE, RsslRDMServiceState::serviceState, and RsslRDMServiceState::status.
Referenced by rsslClearRDMService().
RSSL_VA_API RsslRet rsslDecodeRDMDirectoryMsg (RsslDecodeIterator * pIter, RsslMsg * pMsg, RsslRDMDirectoryMsg * pDirectoryMsg, RsslBuffer * pMemoryBuffer, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Decode Iterator
pDirectoryMsg The RDM Directory Message to be populated
pMemoryBuffer An RsslBuffer pointing to space that may be used as additional storage space for the decoded message.
pError An Error Structure, which will be populated if the decoding fails.
Returns:
RSSL_RET_SUCCESS, if the message was succesfully decoded and correctly followed the RDM.
RSSL_RET_FAILURE, if the message was not successfully decoded or did follow the RDM. Information about the error will be stored in pError.
RSSL_RET_BUFFER_TOO_SMALL, if the size of pMemoryBuffer was not large enough to store all additional data.
See also:
RsslRDMDirectoryMsg
Referenced by rsslDecodeRDMMsg().
RSSL_VA_API RsslRet rsslEncodeRDMDirectoryMsg (RsslEncodeIterator * pEncodeIter, RsslRDMDirectoryMsg * pDirectoryMsg, RsslUInt32 * pBytesWritten, RsslErrorInfo * pError)
Parameters:
pEncodeIter The Encode Iterator
pDirectoryMsg The RDM Directory Message to Encode
pBytesWritten Returns the total number of bytes used to encode the message.
See also:
RsslRDMDirectoryMsg
Referenced by rsslEncodeRDMMsg().
RTR_C_INLINE RsslRet rsslInitDefaultRDMDirectoryRequest (RsslRDMDirectoryRequest * pRequest, RsslInt32 streamId)
See also:
RsslRDMDirectoryRequest, rsslInitDefaultRDMDirectoryRequest
References RsslRDMDirectoryRequest::filter, RsslRDMDirectoryRequest::flags, RDM_DR_RQF_STREAMING, RsslRDMDirectoryRequest::rdmMsgBase, rsslClearRDMDirectoryRequest(), and RsslRDMMsgBase::streamId.