Transport API Value Addded Components Reference Manual: rsslHashTable.h File Reference
rsslHashTable.h File Reference
#include "rtr/rsslTypes.h"
#include "rtr/rsslRetCodes.h"
#include "rtr/rsslQueue.h"
#include "rtr/rsslDataUtils.h"
#include "rtr/rsslErrorInfo.h"
#include <stdlib.h>
Data Structures
struct RsslHashLink
struct RsslHashTable
Defines
#define RSSL_HASH_LINK_TO_OBJECT(__objectType, __link, __pLink) ((__objectType*)((char*)__pLink - offsetof(__objectType, __link)))
#define LOAD_FACTOR 0.75
#define RSSL_HASH_LINK_FROM_QUEUE_LINK(__pLink) ((RsslHashLink*)__pLink)
Typedefs
typedef RsslUInt32 RsslHashSumFunction (void *)
typedef RsslBool RsslHashCompareFunction (void *, void *)
Functions
RTR_C_INLINE void rsslHashLinkInit (RsslHashLink *pLink)
RTR_C_INLINE RsslRet rsslHashTableInit (RsslHashTable *pTable, RsslUInt32 queueCount, RsslHashSumFunction *keyHashFunction, RsslHashCompareFunction *keyCompareFunction, RsslBool dynamicSize, RsslErrorInfo *pErrorInfo)
RTR_C_INLINE RsslRet rsslHashTableCleanup (RsslHashTable *pTable)
RTR_C_INLINE void rsslHashTableInsertLink (RsslHashTable *pTable, RsslHashLink *pLink, void *pKey, RsslUInt32 *pSum)
RTR_C_INLINE void rsslHashTableRemoveLink (RsslHashTable *pTable, RsslHashLink *pLink)
RTR_C_INLINE RsslHashLink * rsslHashTableFind (RsslHashTable *pTable, void *pKey, RsslUInt32 *pSum)
RsslUInt32 rsslHashU16Sum (void *pKey)
RsslBool rsslHashU16Compare (void *pKey1, void *pKey2)
RsslUInt32 rsslHashU32Sum (void *pKey)
RsslBool rsslHashU32Compare (void *pKey1, void *pKey2)
RsslUInt32 rsslHashU64Sum (void *pKey)
RsslBool rsslHashU64Compare (void *pKey1, void *pKey2)
RsslUInt32 rsslHashBufferSum (void *pKey)
RsslBool rsslHashBufferCompare (void *pKey1, void *pKey2)
RTR_C_INLINE RsslRet rsslHashTableResize (RsslHashTable *pTable)
Define Documentation
#define LOAD_FACTOR 0.75
Referenced by rsslHashTableInit(), and rsslHashTableResize().
#define RSSL_HASH_LINK_FROM_QUEUE_LINK (__pLink) ((RsslHashLink*)__pLink)
Referenced by rsslHashTableFind(), and rsslHashTableResize().
#define RSSL_HASH_LINK_TO_OBJECT (__objectType, __link, __pLink) ((__objectType*)((char*)__pLink - offsetof(__objectType, __link)))
Typedef Documentation
typedef RsslBool RsslHashCompareFunction(void *, void *)
typedef RsslUInt32 RsslHashSumFunction(void *)
Function Documentation
RsslBool rsslHashBufferCompare (void * pKey1, void * pKey2)
RsslUInt32 rsslHashBufferSum (void * pKey)
RTR_C_INLINE void rsslHashLinkInit (RsslHashLink * pLink)
References RsslHashLink::hashSum, RsslHashLink::pKey, and RsslHashLink::queueLink.
RTR_C_INLINE RsslRet rsslHashTableCleanup (RsslHashTable * pTable)
References RsslHashTable::queueList.
RTR_C_INLINE RsslHashLink * rsslHashTableFind (RsslHashTable * pTable, void * pKey, RsslUInt32 * pSum)
References RsslHashTable::keyCompareFunction, RsslHashTable::keyHashFunction, RsslHashLink::pKey, RsslHashTable::queueCount, RsslHashTable::queueList, and RSSL_HASH_LINK_FROM_QUEUE_LINK.
RTR_C_INLINE RsslRet rsslHashTableInit (RsslHashTable * pTable, RsslUInt32 queueCount, RsslHashSumFunction * keyHashFunction, RsslHashCompareFunction * keyCompareFunction, RsslBool dynamicSize, RsslErrorInfo * pErrorInfo)
References RsslHashTable::dynamicSize, RsslHashTable::elementCount, RsslHashTable::keyCompareFunction, RsslHashTable::keyHashFunction, LOAD_FACTOR, RsslHashTable::queueCount, RsslHashTable::queueList, RSSL_EIC_FAILURE, rsslSetErrorInfo(), and RsslHashTable::thresholdCapacity.
RTR_C_INLINE void rsslHashTableInsertLink (RsslHashTable * pTable, RsslHashLink * pLink, void * pKey, RsslUInt32 * pSum)
References RsslHashTable::dynamicSize, RsslHashTable::elementCount, RsslHashLink::hashSum, RsslHashTable::keyHashFunction, RsslHashLink::pKey, RsslHashTable::queueCount, RsslHashLink::queueLink, RsslHashTable::queueList, rsslHashTableResize(), and RsslHashTable::thresholdCapacity.
RTR_C_INLINE void rsslHashTableRemoveLink (RsslHashTable * pTable, RsslHashLink * pLink)
References RsslHashTable::elementCount, RsslHashLink::hashSum, RsslHashTable::queueCount, RsslHashLink::queueLink, and RsslHashTable::queueList.
RTR_C_INLINE RsslRet rsslHashTableResize (RsslHashTable * pTable)
References RsslHashLink::hashSum, LOAD_FACTOR, RsslHashTable::queueCount, RsslHashLink::queueLink, RsslHashTable::queueList, RSSL_HASH_LINK_FROM_QUEUE_LINK, and RsslHashTable::thresholdCapacity.
Referenced by rsslHashTableInsertLink().
RsslBool rsslHashU16Compare (void * pKey1, void * pKey2)
RsslUInt32 rsslHashU16Sum (void * pKey)
RsslBool rsslHashU32Compare (void * pKey1, void * pKey2)
RsslUInt32 rsslHashU32Sum (void * pKey)
RsslBool rsslHashU64Compare (void * pKey1, void * pKey2)
RsslUInt32 rsslHashU64Sum (void * pKey)