Transport API Value Addded Components Reference Manual: rsslMemoryPool.h File Reference
rsslMemoryPool.h File Reference
#include "rtr/rsslQueue.h"
#include "rtr/rsslErrorInfo.h"
#include <assert.h>
#include <malloc.h>
Data Structures
struct RsslMemoryPool
struct RsslMemoryBlock
Functions
RTR_C_INLINE RsslRet rsslMemoryPoolInit (RsslMemoryPool *pPool, int blockSize, int blockCount, RsslErrorInfo *pErrorInfo)
RTR_C_INLINE void rsslMemoryPoolCleanup (RsslMemoryPool *pPool)
RTR_C_INLINE void * rsslMemoryPoolGet (RsslMemoryPool *pPool, RsslErrorInfo *pErrorInfo)
RTR_C_INLINE void rsslMemoryPoolPut (RsslMemoryPool *pPool, void *pMemory)
Function Documentation
RTR_C_INLINE void rsslMemoryPoolCleanup (RsslMemoryPool * pPool)
References RsslMemoryPool::blocks.
Referenced by rsslMemoryPoolInit().
RTR_C_INLINE void * rsslMemoryPoolGet (RsslMemoryPool * pPool, RsslErrorInfo * pErrorInfo)
References RsslMemoryPool::blocks, RsslMemoryPool::blockSize, RSSL_EIC_FAILURE, and rsslSetErrorInfo().
RTR_C_INLINE RsslRet rsslMemoryPoolInit (RsslMemoryPool * pPool, int blockSize, int blockCount, RsslErrorInfo * pErrorInfo)
References RsslMemoryPool::blocks, RsslMemoryPool::blockSize, RsslMemoryBlock::qlPool, RSSL_EIC_FAILURE, rsslMemoryPoolCleanup(), and rsslSetErrorInfo().
RTR_C_INLINE void rsslMemoryPoolPut (RsslMemoryPool * pPool, void * pMemory)
References RsslMemoryPool::blocks.