Transport API Value Addded Components Reference Manual: rsslHeapBuffer.h File Reference
rsslHeapBuffer.h File Reference
#include "rtr/rsslTypes.h"
#include <malloc.h>
Functions
RTR_C_INLINE void rsslHeapBufferReset (RsslBuffer *pBuffer, RsslBuffer *pMemBuffer)
RTR_C_INLINE RsslRet rsslHeapBufferInit (RsslBuffer *pBuffer, RsslUInt32 length)
RTR_C_INLINE void rsslHeapBufferCleanup (RsslBuffer *pBuffer)
RTR_C_INLINE RsslRet rsslHeapBufferResize (RsslBuffer *pBuffer, RsslUInt32 length, RsslBool keepData)
RTR_C_INLINE RsslRet rsslHeapBufferCreateCopy (RsslBuffer *pOutBuffer, RsslBuffer *pInBuffer)
RTR_C_INLINE RsslRet rsslHeapBufferCopy (RsslBuffer *pOutBuffer, RsslBuffer *pInBuffer, RsslBuffer *pMemBuffer)
Function Documentation
RTR_C_INLINE void rsslHeapBufferCleanup (RsslBuffer * pBuffer)
RTR_C_INLINE RsslRet rsslHeapBufferCopy (RsslBuffer * pOutBuffer, RsslBuffer * pInBuffer, RsslBuffer * pMemBuffer)
References rsslHeapBufferInit(), and rsslHeapBufferReset().
RTR_C_INLINE RsslRet rsslHeapBufferCreateCopy (RsslBuffer * pOutBuffer, RsslBuffer * pInBuffer)
References rsslHeapBufferInit().
RTR_C_INLINE RsslRet rsslHeapBufferInit (RsslBuffer * pBuffer, RsslUInt32 length)
Referenced by rsslHeapBufferCopy(), and rsslHeapBufferCreateCopy().
RTR_C_INLINE void rsslHeapBufferReset (RsslBuffer * pBuffer, RsslBuffer * pMemBuffer)
Referenced by rsslHeapBufferCopy().
RTR_C_INLINE RsslRet rsslHeapBufferResize (RsslBuffer * pBuffer, RsslUInt32 length, RsslBool keepData)